(()=>{
'use strict';
const C=window.RenShengCore;
const KEY='rensheng_v1_state';
let state=C.normalize(load());
let win=null;
let browserRoute='home';
let anchorOpen=false;
let historyStack=[];
let historyIndex=-1;
let minimizedWin=null;
let winMax=false;
let browserTabs=['home'];
let idleTimer=null;
const app=document.getElementById('app');
const blackout=document.getElementById('blackout');

function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){return null}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function reset(){localStorage.removeItem(KEY);state=C.fresh();win=null;minimizedWin=null;winMax=false;browserRoute='home';browserTabs=['home'];historyStack=[];historyIndex=-1;render();}
function mark(k){state=C.mark(state,k);save();renderAnchor();}
function has(k){return C.has(state,k)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function pulse(){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=610;g.gain.setValueAtTime(.018,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.16);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.17)}catch(e){}}
function lowTone(){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=62;g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+2.2);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+2.3)}catch(e){}}
function clock(){const d=new Date();return d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}
function anchor(){return C.anchor(state)}
function armIdleHint(){
 clearTimeout(idleTimer);
 idleTimer=setTimeout(()=>{
  if(state.ended)return;
  const b=document.getElementById('anchorToggle'); if(b)b.classList.add('idle-hint');
 },180000);
}
function noteActivity(){armIdleHint()}

const normalNews=[
 ['1996-11-29','市公交公司增开冬季早班车','民生'],['1996-11-28','鹤宁纺织厂完成锅炉改造','经济'],['1996-11-27','南关多名儿童已与家属取得联系','社会'],['1996-11-26','校方提醒家长接送低年级学生','教育'],['1996-11-25','关于南关“怪老人”传言的情况说明','社会'],['1996-11-24','南关五名儿童一度与家长失去联系','社会'],['1996-11-23','冬储白菜进入集中上市期','民生'],['1996-11-22','青年宫周末开放乒乓球馆','文体'],['1996-11-21','鹤宁今冬首场降雪预计周末到来','天气'],['1996-11-20','市环卫处调整冬季清扫时间','民生'],['1996-11-18','二轻系统举办职工书画展','文体'],['1996-11-15','南关旧街路灯检修本周完成','民生'],['1996-11-14','市百货大楼冬装展销本周开幕','商业'],['1996-11-13','东河路部分路段夜间停电检修','民生'],['1996-11-12','市少年宫举办冬季美术班','教育'],['1996-11-11','南关菜市场完成排水沟整修','民生'],['1996-11-09','鹤宁队客场战平北川队','文体'],['1996-11-07','市图书馆延长周末开放时间','文化'],['1996-11-05','冬季供暖试压工作全面展开','民生']
];
const schoolNotices=[
 ['2012-06-28','关于暑期校舍安全检查的通知'],['2011-09-01','新学期开学工作安排'],['2010-12-03','冬季传染病防控告家长书'],['2009-05-12','校园消防疏散演练情况'],['2008-10-18','第十七届田径运动会成绩'],['2006-09-10','优秀教师表彰名单'],['2003-03-07','春季植树活动安排'],['1999-12-20','校史资料整理征集启事'],['1997-03-03','新学期教研组活动安排'],['1996-12-02','关于加强低年级放学管理的通知'],['1996-11-18','卫生室冬季常见病预防提示'],['1996-10-12','少先队大队委改选结果'],['1996-09-02','新学期值周安排'],['1996-06-28','暑假前安全教育安排'],['1996-05-31','庆“六一”文艺汇演节目单']
];
const forumThreads=[
 ['2012-10-04','南关早市附近昨天是不是在找孩子？','槐树下喝茶',18],['2012-09-28','二路车终点到底搬哪儿了','老何修车',9],['2008-04-12','求租南关一室一厅','小北风',12],['2005-11-21','说说九几年那个猫脸老太太到底怎么传起来的','锅炉房老李',47],['2003-06-07','鹤宁二小以前是不是有个后门？','南关照相馆',21],['2001-02-03','槐树巷拆迁前老门牌谁还记得','旧邮局',33],['1999-08-16','南关最好吃的糖糕是哪家','三轮车王师傅',26],['1998-12-11','寻找老同学：二小89级三班','梅子',14],['2009-12-02','南关哪家修收音机还行','东河口',7],['2007-06-18','早市搬了以后买菜真麻烦','小叶子',22],['2006-03-11','谁有旧二路车时刻表','二厂宿舍',5],['2004-09-19','求推荐给孩子补习作文的老师','秋雨',16],['2002-12-27','南关澡堂什么时候关门','老邢',11],['2000-05-14','街坊们有谁会修凤凰车','一把扳手',8]
];
const cultureEntries=[
 ['民俗','鹤宁旧俗中的守灵禁忌','2007-03-16'],['方言','南关街巷旧称与俗称小考','2008-09-21'],['庙会','城隍庙会旧照片整理（一）','2006-05-02'],['节气','冬至前后的家庭饮食习惯','2009-12-20'],['地方志','槐树巷、井台胡同旧门牌沿革','2011-07-04'],['民俗','儿童乳名与避讳称呼','2005-08-19'],['口述史','南关旧街居民生活片段','2010-02-11'],['非遗','鹤宁剪纸纹样采集记录','2008-01-08'],['馆讯','2009年地方资料捐赠目录','2010-01-16'],['方言','老城区儿童称谓小记','2007-11-02'],['街巷','东河路沿革简表','2011-03-14']
];
const libEntries=[
 ['HN-LD-1996-112','《鹤宁晚报》1996年11月合订本','报刊缩微'],['HN-NG-2001-017','《南关街道旧门牌对照表（1987-2000）》','地方文献'],['HN-EDU-1996-04','鹤宁第二小学 1996 年校务附件镜像','教育档案'],['HN-MEM-2010-09','南关居民口述资料第九辑','口述史'],['HN-MAP-1994-02','鹤宁市区街巷图 1994 修订版','地图'],['HN-ALM-2008-01','鹤宁地方习俗资料汇编','地方志'],['HN-BUS-1998-03','鹤宁市公共交通线路资料（1998）','交通史料'],['HN-IMG-2004-11','南关街道居民捐赠照片目录','图片目录'],['HN-COM-2007-06','旧城改造社区资料汇编','社区资料'],['HN-EDU-2002-18','鹤宁市小学名录（2002）','教育资料']
];

function render(){
 if(state.ended){renderEnd();return}
 app.innerHTML=desktopHTML()+(win?windowHTML(win):'');
 bindDesktop();
 renderAnchor();
 setTimeout(()=>document.getElementById('boot')?.classList.add('hide'),350);
}
function desktopHTML(){
 const a=anchor();
 const activeTask=win?taskLabel(win):(minimizedWin?taskLabel(minimizedWin):'');
 return `<div class="os"><div class="desktop">
   <div class="desk-icons">
    ${deskIcon('computer','computer','我的电脑')}
    ${deskIcon('trash','recycle','回收站')}
    ${deskIcon('folder','syfolder','沈妍的资料')}
    ${deskIcon('folder','unsorted','未整理')}
    ${deskIcon('browser','browser','Internet Explorer')}
    ${deskIcon('tmp','doc','维修说明.txt')}
   </div>
   <div id="startMenu" class="start-menu" aria-hidden="true">
    <div class="start-user"><div class="start-avatar">沈</div><b>沈妍</b></div>
    <div class="start-columns"><div class="start-left">
      <button data-open="browser"><img src="assets/icons/browser.png" alt="">Internet Explorer</button>
      <button data-open="doc"><img src="assets/icons/tmp.png" alt="">记事本</button>
      <hr><button data-open="syfolder"><img src="assets/icons/folder.png" alt="">我的文档</button>
      <button data-open="photos"><img src="assets/icons/photo.png" alt="">我的图片</button>
    </div><div class="start-right">
      <button data-open="computer">我的电脑</button><button data-open="control">控制面板</button><hr><button data-open="search">搜索</button><button data-open="run">运行...</button>
    </div></div>
    <div class="start-footer"><span>注销</span><span>关闭计算机</span></div>
   </div>
 </div>
 <div class="taskbar"><button class="start-button" id="startButton" aria-label="开始"><span class="start-flag"></span><b>开始</b></button><div class="quick-launch"><button data-open="browser" title="Internet Explorer"><img src="assets/icons/browser.png" alt=""></button><button data-open="syfolder" title="我的文档"><img src="assets/icons/folder.png" alt=""></button></div>${activeTask?`<button class="task-app ${minimizedWin&&!win?'minimized-task':''}" ${minimizedWin&&!win?`data-restore="${minimizedWin}"`:`data-open="${win||minimizedWin}"`}><span>${esc(activeTask)}</span></button>`:''}<div class="tray"><span class="tray-net"></span><span class="tray-speaker"></span><button id="anchorToggle" class="tray-help" title="需要一点提示时点这里">?</button><div class="clock">${clock()}<br>2026/09/13</div></div></div>
 <div id="anchorPanel" class="anchor-panel xp-balloon"><button class="balloon-close" id="anchorClose">×</button><b>${esc(a[0])}</b><div class="sub">${esc(a[1])}</div></div>
 </div>`;
}
function taskLabel(id){return ({computer:'我的电脑',recycle:'回收站',syfolder:'沈妍的资料',unsorted:'未整理',photos:'照片',folder:'1996资料',thesis:'毕业论文.doc',photo:'IMG_2002.jpg',timeline:'调查记录.xls',private:'旧电脑备份',doc:'维修说明.txt',control:'控制面板',help:'帮助和支持',search:'搜索',run:'运行',browser:'Internet Explorer'}[id]||String(id).replace(/^local:/,''))}
function deskIcon(cls,id,label){return `<button class="desk-icon" data-open="${id}" title="双击打开 ${esc(label)}"><img class="desk-ico-img" src="assets/icons/${cls}.png" alt=""><span>${esc(label)}</span></button>`}
function deskDecor(cls,label){return deskIcon(cls,'doc',label)}
function bindDesktop(){
 const coarse=matchMedia('(pointer:coarse)').matches;
 document.querySelectorAll('[data-open]:not(.desk-icon)').forEach(b=>b.onclick=e=>{e.stopPropagation();openWin(b.dataset.open)});
 document.querySelectorAll('.desk-icon').forEach(b=>{
   b.onclick=e=>{e.stopPropagation();document.querySelectorAll('.desk-icon.selected').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');if(coarse)openWin(b.dataset.open)};
   b.ondblclick=e=>{e.preventDefault();e.stopPropagation();openWin(b.dataset.open)};
 });
 document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{win=b.dataset.restore;minimizedWin=null;render()});
 const sb=document.getElementById('startButton'), sm=document.getElementById('startMenu');
 if(sb&&sm) sb.onclick=e=>{e.stopPropagation();sm.classList.toggle('show');sm.setAttribute('aria-hidden',sm.classList.contains('show')?'false':'true')};
 const at=document.getElementById('anchorToggle'); if(at)at.onclick=()=>{anchorOpen=!anchorOpen;renderAnchor()}; document.getElementById('anchorClose')?.addEventListener('click',()=>{anchorOpen=false;renderAnchor()});
 document.querySelector('.desktop')?.addEventListener('click',e=>{if(!e.target.closest('.start-menu')&&!e.target.closest('#startButton'))document.getElementById('startMenu')?.classList.remove('show')});
}
function renderAnchor(){const p=document.getElementById('anchorPanel');if(!p)return;const a=anchor();p.innerHTML=`<button class="balloon-close" id="anchorClose">×</button><b>${esc(a[0])}</b><div class="sub">${esc(a[1])}</div>`;p.classList.toggle('show',anchorOpen);document.getElementById('anchorClose')?.addEventListener('click',()=>{anchorOpen=false;renderAnchor()});const t=document.getElementById('anchorToggle');if(t&&anchorOpen)t.classList.remove('idle-hint')}
function openWin(id){
 if(id==='browser'){openBrowser(browserRoute);return}
 if(id==='cache'){triggerBlackout();return}
 minimizedWin=null;winMax=false;win=id;render();
}
function closeWin(){if(win==='timeline'&&has('final_date')&&has('final_photo')){state.ended=true;save();win=null;render();return}win=null;minimizedWin=null;winMax=false;render()}
function windowHTML(id){
 let title='',body='',small=false,type='explorer',toolbar='',menubar='',status='就绪';
 const xpMenu='<div class="classic-menu">文件(F)　编辑(E)　查看(V)　收藏(A)　工具(T)　帮助(H)</div>';
 if(id.startsWith('local:')){const sp=localFileSpec(id.slice(6));title=sp.title;type=sp.type||'notepad';menubar=sp.menubar||'';toolbar=sp.toolbar||'';body=sp.body||'';status=sp.status||'就绪';}
 const explorerToolbar=(path)=>`<div class="win-toolbar xp-toolbar"><button class="xp-tool nav-arrow">←</button><button class="xp-tool nav-arrow muted-tool">→</button><button class="xp-tool nav-arrow">↑</button><span class="xp-sep"></span><button class="xp-tool wide"><span class="mini-search"></span>搜索</button><button class="xp-tool wide"><img src="assets/icons/folder.png" alt="">文件夹</button><span class="xp-sep"></span><div class="crumbbox"><b>地址</b>　${path}</div><button class="xp-go">转到</button></div>`;
 if(id==='doc'){title='维修说明.txt - 记事本';small=true;type='notepad';menubar='<div class="classic-menu">文件(F)　编辑(E)　格式(O)　查看(V)　帮助(H)</div>';body=`<div class="note-paper notepad-paper">送修时机器外壳和屏幕右侧已有摔裂痕迹，硬盘检测未发现坏道。<br><br>按家属要求，只做了开机修复和资料镜像，没有移动、重命名或删除原文件。旧版浏览器目前只能读取本机保存过的缓存页面，网络连接未启用。<br><br>Internet 同步用户：sy0718（仅恢复本地书签与历史）。<br><br>如果备份完成，请直接关机，不要运行磁盘清理。<br><br>— 鹤宁科维电脑维修　2026.09.12</div><div class="notepad-footer"><button id="resetBtn" class="classic-button">清除本地进度重新开始</button></div>`}
 if(id==='computer'){title='我的电脑';type='explorer';menubar=xpMenu;toolbar=explorerToolbar('我的电脑');body=myComputerHTML();status='4 个对象'}
 if(id==='recycle'){title='回收站';type='explorer';menubar=xpMenu;toolbar=explorerToolbar('回收站');body=recycleHTML();status='回收站中有 6 个对象'}
 if(id==='syfolder'){title='沈妍的资料';type='explorer';menubar=xpMenu;toolbar=explorerToolbar('C:\\Documents and Settings\\沈妍\\我的文档\\沈妍的资料');body=syFolderHTML();status='3 个对象'}
 if(id==='unsorted'){title='未整理';type='explorer';menubar=xpMenu;toolbar=explorerToolbar('C:\\Documents and Settings\\沈妍\\桌面\\未整理');body=unsortedHTML();status='3 个对象'}
 if(id==='photos'){title='照片';type='explorer';menubar=xpMenu;toolbar=explorerToolbar('C:\\Documents and Settings\\沈妍\\我的文档\\我的图片');body=photosFolderHTML();status='3 个对象'}
 if(id==='folder'){title='1996资料';type='explorer';menubar=xpMenu;toolbar=explorerToolbar('C:\\Documents and Settings\\沈妍\\我的文档\\沈妍的资料\\1996资料');body=folderHTML();status='3 个对象'}
 if(id==='thesis'){title='毕业论文.doc - Microsoft Word';type='word-viewer';menubar='<div class="classic-menu">文件(F)　编辑(E)　视图(V)　插入(I)　格式(O)　工具(T)　表格(A)　窗口(W)　帮助(H)</div>';toolbar='<div class="word-toolbar"><button>新建</button><button>打开</button><button>保存</button><button>打印</button><span class="xp-sep"></span><span>样式：正文　字体：宋体　字号：小四　<b>B</b>　<i>I</i>　<u>U</u></span></div>';body=thesisHTML();status='第 1 页，共 42 页　　1 节'}
 if(id==='photo'){title='IMG_2002.jpg - Windows 图片和传真查看器';type='photo-viewer';menubar='';toolbar='<div class="photo-tools"><button>上一张</button><button>下一张</button><button>左转</button><button>右转</button><button>放大</button><button>缩小</button><button>打印</button><button>保存</button></div>';body=photoHTML();status='IMG_2002.jpg'}
 if(id==='timeline'){title='调查记录.xls - Microsoft Excel';type='sheet-viewer';menubar='<div class="classic-menu">文件(F)　编辑(E)　视图(V)　插入(I)　格式(O)　工具(T)　数据(D)　窗口(W)　帮助(H)</div>';toolbar='<div class="excel-ribbon classic-toolbar"><button>新建</button><button>打开</button><button>保存</button><button>打印</button><span class="xp-sep"></span><span>字体：宋体　字号：10　<b>B</b>　<i>I</i>　<u>U</u>　Σ</span></div><div class="formula-bar"><span class="namebox-mini">A1</span><span>fx</span><div>日期核对</div></div>';body=timelineHTML();status='就绪'}
 if(id==='private'){title='旧电脑备份';type='private-window';menubar='<div class="classic-menu">文件(F)　安全(S)　帮助(H)</div>';body=privateLoginHTML();status='本地加密文件'}
 if(id==='work'){title='工作';type='explorer';menubar=xpMenu;toolbar=explorerToolbar('C:\\Documents and Settings\\沈妍\\我的文档\\工作');body=workHTML();status='7 个对象'}
 if(id==='travel'){title='旅行';type='explorer';menubar=xpMenu;toolbar=explorerToolbar('C:\\Documents and Settings\\沈妍\\我的文档\\旅行');body=travelHTML();status='13 个对象'}
 if(id==='downloads'){title='下载';type='explorer';menubar=xpMenu;toolbar=explorerToolbar('C:\\Documents and Settings\\沈妍\\我的文档\\下载');body=downloadsHTML();status='9 个对象'}
 if(id==='control'){title='控制面板';type='control-window';body=controlHTML();status='经典视图'}
 if(id==='systeminfo'){title='系统属性';small=true;type='systeminfo-window';body=systemInfoHTML();status=''}
 if(id==='help'){title='帮助和支持中心';type='help-window';body=helpHTML();status='Windows 帮助和支持'}
 if(id==='search'){title='搜索结果';type='search-window';body=searchHTML();status='准备搜索'}
 if(id==='run'){title='运行';small=true;type='run-window';body=runHTML();status=''}
 if(id==='qq'){title='腾讯QQ';small=true;type='qq-window';body=qqHTML();status='离线'}
 if(id==='media'){title='Windows Media Player';type='media-window';body=mediaHTML();status='停止'}
 if(id==='zip'){title='旧照片.zip - WinRAR';type='zip-window';menubar='<div class="classic-menu">文件(F)　命令(C)　工具(T)　收藏夹(F)　选项(O)　帮助(H)</div>';body=zipHTML();status='压缩文件，共 8 个对象'}
 return `<section class="window center ${winMax?'maximized ':''}${small?'small ':''}${type}"><div class="titlebar"><span class="window-app-icon ${type}"></span><strong>${esc(title)}</strong><button class="win-min" id="winMin" aria-label="最小化">_</button><button class="win-max" id="winMax" aria-label="最大化">□</button><button class="win-close" id="winClose" aria-label="关闭">×</button></div>${menubar}${toolbar}<div class="window-body">${body}</div><div class="window-status">${status}</div></section>`;
}
function bindWindow(){
 document.getElementById('winClose')?.addEventListener('click',closeWin);
 document.getElementById('winMin')?.addEventListener('click',()=>{minimizedWin=win;win=null;render()});
 document.getElementById('winMax')?.addEventListener('click',()=>{winMax=!winMax;render()});
 document.getElementById('resetBtn')?.addEventListener('click',()=>confirm('确定清除当前进度？')&&reset());
 document.querySelectorAll('.window [data-open]').forEach(b=>b.onclick=()=>openWin(b.dataset.open));
}
function xpExplorerLayout(sideTitle,sideItems,main){return `<div class="explorer-layout"><aside class="explorer-tree xp-tasks"><div class="xp-taskbox"><h4>${sideTitle}</h4>${sideItems}</div><div class="xp-taskbox pale"><h4>其他位置</h4><button data-open="syfolder">我的文档</button><button data-open="computer">我的电脑</button><button data-open="recycle">回收站</button></div></aside><section class="explorer-main">${main}<div id="localPreview" class="local-preview"></div></section></div>`}
function myComputerHTML(){return xpExplorerLayout('系统任务','<button data-open="systeminfo">查看系统信息</button><button data-open="control">添加或删除程序</button><button data-open="control">更改一个设置</button>',`<h3 class="explorer-section-title">存储在此计算机上的文件</h3><div class="xp-drive-list"><button class="xp-drive" data-open="syfolder"><img src="assets/icons/folder.png"><span><b>沈妍的文档</b><small>文件夹</small></span></button><button class="xp-drive" data-open="photos"><img src="assets/icons/photo.png"><span><b>共享文档</b><small>图片与扫描件</small></span></button></div><h3 class="explorer-section-title">硬盘驱动器</h3><div class="xp-drive-list"><button class="xp-drive" data-local="driveC"><img src="assets/icons/drive_c.png"><span><b>本地磁盘 (C:)</b><small>38.2 GB 可用，共 74.5 GB</small><i><em style="width:48%"></em></i></span></button><button class="xp-drive" data-local="driveD"><img src="assets/icons/drive_d.png"><span><b>资料盘 (D:)</b><small>9.1 GB 可用，共 19.5 GB</small><i><em style="width:54%"></em></i></span></button></div><h3 class="explorer-section-title">有可移动存储的设备</h3><div class="xp-drive-list"><button class="xp-drive" data-local="dvd"><img src="assets/icons/cd.png"><span><b>DVD 驱动器 (E:)</b><small>没有光盘</small></span></button></div>`)}
function recycleHTML(){return xpExplorerLayout('回收站任务','<button class="static-task">清空回收站</button><button class="static-task">还原所有项目</button>',`<div class="details-list"><div class="details-head"><span>名称</span><span>原位置</span><span>删除日期</span><span>大小</span></div>${[['IMG_0891副本.jpg','C:\\Documents and Settings\\沈妍\\桌面','2026-08-18','1.8 MB'],['淘宝订单截图.bmp','D:\\杂项','2026-08-04','824 KB'],['论坛摘录_旧.txt','D:\\未整理','2026-07-22','4 KB'],['meeting_final2.doc','我的文档','2026-07-11','96 KB'],['公交站牌.jpg','我的图片','2026-08-02','742 KB'],['新建文本文档.txt','桌面','2026-06-19','0 KB']].map(x=>`<div class="details-row"><span><img src="assets/icons/doc.png">${x[0]}</span><span>${x[1]}</span><span>${x[2]}</span><span>${x[3]}</span></div>`).join('')}</div>`)}
function syFolderHTML(){return xpExplorerLayout('文件和文件夹任务','<button class="static-task">新建文件夹</button><button class="static-task">按名称排列</button>',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-open="folder"><img src="assets/icons/folder.png"><span>1996资料</span></button><button class="explorer-file" data-open="thesis"><img src="assets/icons/doc.png"><span>毕业论文.doc</span></button><button class="explorer-file" data-open="photos"><img src="assets/icons/folder.png"><span>照片资料</span></button></div>`)}
function unsortedHTML(){return xpExplorerLayout('文件和文件夹任务','<button class="static-task">新建文件夹</button><button class="static-task">按日期排列</button>',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-local="unsorted1"><img src="assets/icons/tmp.png"><span>待核_1014.txt</span></button><button class="explorer-file" data-local="bus"><img src="assets/icons/pdf.png"><span>公交线路_旧二路.pdf</span></button><button class="explorer-file" data-local="webcache"><img src="assets/icons/folder.png"><span>网页缓存</span></button></div>`)}
function photosFolderHTML(){
 return xpExplorerLayout('图片任务','<button class="static-task">以幻灯片方式查看</button><button class="static-task">打印图片</button>',`<div class="photo-folder-grid compact-photos"><button class="photo-thumb" data-local="photoSchool"><img src="assets/school_old.jpg"><span>IMG_0187.jpg</span></button><button class="photo-thumb" data-local="photoStreet"><img src="assets/old_street.jpg"><span>scan_南关街_01.jpg</span></button><button class="photo-thumb" data-local="photoFestival"><img src="assets/festival.jpg"><span>2006_庙会_捐赠.jpg</span></button></div>`)}
function thesisHTML(){return `<div class="word-workarea"><div class="word-ruler"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span>8</span><span>9</span><span>10</span><span>11</span><span>12</span></div><article class="word-page"><h1>地方都市传说传播机制中的<br>记忆重构与媒介再生产</h1><p class="word-meta">本科毕业论文　　沈妍<br>指导教师：周老师　　2026 年 4 月（初稿）</p><h2>摘　要</h2><p>本文以地方性都市传说为研究对象，讨论报刊、口述记忆与网络论坛在叙事扩散过程中如何互相改写。研究发现，同一事件在不同记录体系中常出现人数、地点与称谓的偏差，这类偏差既可能来自统计口径，也可能被后来的讲述重新组织。</p><p>论文案例均来自公开材料，涉及真实人物的部分已作匿名处理。</p><p class="word-keywords"><b>关键词：</b>都市传说；地方记忆；网络论坛；媒介叙事</p><div class="page-break-line">— 1 —</div></article></div>`}
function folderHTML(){
 return xpExplorerLayout('文件和文件夹任务','<button class="static-task">新建文件夹</button><button class="static-task">按类型排列</button>',`<div class="explorer-icon-grid rich compact-files">
      <button class="explorer-file" data-local="clip"><img src="assets/icons/tmp.png" alt=""><span>剪报索引_1996.txt</span></button>
      <button class="explorer-file" data-local="papers"><img src="assets/icons/folder.png" alt=""><span>报纸扫描</span></button>
      <button class="explorer-file" data-local="map"><img src="assets/icons/imagefile.png" alt=""><span>南关地图_1994.jpg</span></button>
    </div>`);
}
function openLocal(type){minimizedWin=null;winMax=false;win='local:'+type;render()}
function localFileSpec(type){
 const notepad=(title,html)=>({title:title+' - 记事本',type:'notepad',menubar:'<div class="classic-menu">文件(F)　编辑(E)　格式(O)　查看(V)　帮助(H)</div>',toolbar:'',body:`<div class="note-paper notepad-paper local-doc">${html}</div>`,status:'Windows (CRLF)　ANSI'});
 const image=(title,src,caption)=>({title:title+' - Windows 图片和传真查看器',type:'photo-viewer',menubar:'',toolbar:'<div class="photo-tools"><button>上一张</button><button>下一张</button><button>左转</button><button>右转</button><button>放大</button><button>缩小</button><button>打印</button></div>',body:`<div class="single-photo-view"><img src="${src}" alt=""><div class="single-photo-caption">${caption}</div></div>`,status:title});
 const explorer=(title,path,main,count)=>({title,type:'explorer',menubar:'<div class="classic-menu">文件(F)　编辑(E)　查看(V)　收藏(A)　工具(T)　帮助(H)</div>',toolbar:`<div class="win-toolbar xp-toolbar"><button class="xp-tool nav-arrow">←</button><button class="xp-tool nav-arrow">→</button><button class="xp-tool nav-arrow">↑</button><span class="xp-sep"></span><button class="xp-tool wide"><span class="mini-search"></span>搜索</button><button class="xp-tool wide"><img src="assets/icons/folder.png" alt="">文件夹</button><span class="xp-sep"></span><div class="crumbbox"><b>地址</b>　${path}</div></div>`,body:xpExplorerLayout('文件和文件夹任务','<button class="static-task">新建文件夹</button><button class="static-task">按名称排列</button>',main),status:(count||0)+' 个对象'});
 if(type==='clip')return notepad('剪报索引_1996.txt',`1996 / 南关　剪报索引<br><br>11/23　冬储白菜集中上市（南关早市）<br>11/24　五名儿童一度与家长失去联系<br>11/25　“怪老人”传言情况说明<br>11/26　二小加强低年级放学管理<br>11/27　多名儿童已与家属取得联系<br><br>报纸原件：市图书馆缩微胶卷，11月合订本。<br>数字版：<button class="file-link" data-web="news">archive.heningdaily.local</button><br><br>手写补记：11/24那篇先写五个，后面的数字又变了。二小也有一份当周的旧附件，没抄进来。`);
 if(type==='hehui')return notepad('户籍摘录_何惠.txt',`户籍资料摘录（手抄）<br><br>姓名：何惠<br>出生：1988-03-09<br>原住址：南关区东河路42号<br>1996年底迁出。<br><br>妈只说她小时候在南关走丢过一回，从来没提过转学。我以前问过，她只说记不清了。`);
 if(type==='unsorted1')return notepad('待核_1014.txt',`10/14<br><br>旧箱子里的剪报只整理到11月27日。妈总说小时候那次已经记不清了，可户籍上年底就迁了出去。<br><br>先别往那些传言上想，把能对上的日期和名字对完再说。`);
 if(type==='unsorted2')return notepad('旧论坛登录.txt',`南关人家<br>bbs.nanguan.local<br><br>账号：sy0718<br><br>旧密码已经失效。浏览器里还能打开部分公开帖子。`);
 if(type==='bus')return {title:'公交线路_旧二路.pdf - Adobe Reader',type:'pdf-window',menubar:'<div class="classic-menu">文件(F)　编辑(E)　查看(V)　文档(D)　工具(T)　窗口(W)　帮助(H)</div>',toolbar:'<div class="pdf-toolbar"><button>打开</button><button>保存副本</button><button>打印</button><span>第 1 / 2 页　100%</span></div>',body:`<div class="pdf-page"><h2>鹤宁市公共汽车旧线路表</h2><p>资料年份：1998</p><hr><p><b>2路：</b>火车站 — 百货大楼 — 南关早市 — 东河路 — <b>旧二路终点</b></p><p>首班 06:10　末班 19:10</p><p class="pencil-note">打印件页边手写：2012还这么叫的人，多半是老住户。</p><div class="pdf-foot">鹤宁市公共交通资料汇编 · 第32页</div></div>`,status:'1 / 2　8.5 × 11.7 in'};
 if(type==='map'||type==='mapprint')return image(type==='map'?'南关地图_1994.jpg':'地图打印.pdf','assets/map_1994.jpg',type==='map'?'纸本地图扫描。槐树巷附近有铅笔圈注。':'打印日期：2012-10-05。第2页为南关旧街放大图。');
 if(type==='photoSchool')return image('IMG_0187.jpg','assets/school_old.jpg','【资料图】鹤宁第二小学旧校舍，旧站缓存恢复，拍摄年代约2000年代初。');
 if(type==='photoStreet')return image('scan_南关街_01.jpg','assets/old_street.jpg','【资料图】南关旧街街景，扫描自地方报刊旧版。');
 if(type==='photoFestival')return image('2006_庙会_捐赠.jpg','assets/festival.jpg','【馆藏图】南关庙会现场，2006，鹤宁地方文化馆数字资料。');
 if(type==='papers'){
   return explorer('报纸扫描','C:\\...\\1996资料\\报纸扫描',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-local="scan1124"><img src="assets/icons/imagefile.png"><span>1996-11-24_03版.tif</span></button><button class="explorer-file" data-local="scan1125"><img src="assets/icons/imagefile.png"><span>1996-11-25_02版.tif</span></button><button class="explorer-file" data-local="scan1127"><img src="assets/icons/imagefile.png"><span>1996-11-27_03版.tif</span></button></div>`,3);
 }
 if(type==='schoolfiles'){
   return explorer('学校档案','C:\\...\\1996资料\\学校档案',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-local="schoolIndex"><img src="assets/icons/tmp.png"><span>附件目录.txt</span></button><button class="explorer-file" data-local="classList"><img src="assets/icons/sheet.png"><span>三年级点名册.xls</span></button></div>`,2);
 }
 if(type==='policefiles'){
   return explorer('派出所材料','C:\\...\\1996资料\\派出所材料',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-local="policeNote"><img src="assets/icons/tmp.png"><span>编号对照_手抄.txt</span></button></div>`,1);
 }
 if(type==='schoolIndex')return notepad('附件目录.txt',`1996_点名册.xls<br>1996-11-25_三年级考勤汇总.xls<br>1996-12_转学办理汇总.xls<br>班主任工作记录_1996-11-27.pdf<br><br>扫描件来源：校史资料整理批次（2009）。`);
 if(type==='classList')return {title:'三年级点名册.xls - Microsoft Excel',type:'sheet-viewer',menubar:'<div class="classic-menu">文件(F)　编辑(E)　视图(V)　插入(I)　格式(O)　工具(T)　数据(D)　窗口(W)　帮助(H)</div>',toolbar:'<div class="excel-ribbon classic-toolbar"><button>打开</button><button>保存</button><button>打印</button><span>宋体　10　<b>B</b>　<i>I</i></span></div>',body:`<div class="timeline-wrap"><table class="excel-grid"><thead><tr><th></th><th>A</th><th>B</th><th>C</th></tr><tr><th>1</th><th>姓名</th><th>班级</th><th>备注</th></tr></thead><tbody><tr><th>2</th><td>何惠</td><td>三年级二班</td><td></td></tr><tr><th>3</th><td>孙雪</td><td>三年级二班</td><td></td></tr><tr><th>4</th><td>刘强</td><td>三年级二班</td><td></td></tr></tbody></table></div>`,status:'就绪'};
 if(type==='policeNote')return notepad('编号对照_手抄.txt',`NG961123-07<br>NG961123-11<br>NG961124-02<br>NG961124-04<br><br>旁边有一行手写："何家那条没找到正式编号，得看值班摘要。"`);
 if(type==='webcache'){
   const recovered=has('blackout')?'<button class="explorer-file" data-local="recovered2012"><img src="assets/icons/folder.png"><span>恢复文件_2012</span></button>':'';
   const corrupt=has('address17')&&has('folkname')&&!has('blackout')?'<button class="explorer-file" data-cache="1"><img src="assets/icons/tmp.png"><span>cache_1127.tmp</span></button>':'';
   const visited=[has('news5')?['news','鹤宁晚报.url']:null,has('school6')?['school','鹤宁二小.url']:null,has('zhao')?['forum','南关人家.url']:null,has('folkname')?['culture','地方文化馆.url']:null].filter(Boolean).map(x=>`<button class="explorer-file" data-web="${x[0]}"><img src="assets/icons/browser.png"><span>${x[1]}</span></button>`).join('');
   return explorer('网页缓存','C:\\...\\未整理\\网页缓存',`<div class="explorer-icon-grid rich compact-files">${visited||'<div class="empty-folder">没有可用的收藏夹快捷方式。</div>'}${corrupt}${recovered}</div>`,(visited?visited.match(/explorer-file/g)?.length||0:0)+(corrupt?1:0)+(recovered?1:0));
 }
 if(type==='recovered2012')return explorer('恢复文件_2012','C:\\...\\未整理\\网页缓存\\恢复文件_2012',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-local="sicknote"><img src="assets/icons/imagefile.png"><span>请假单_2012.jpg</span></button><button class="explorer-file" data-local="notice"><img src="assets/icons/doc.png"><span>寻人启事_排版稿.doc</span></button><button class="explorer-file" data-local="restorelog"><img src="assets/icons/tmp.png"><span>restore.log</span></button></div>`,3);
 if(type==='restorelog')return notepad('restore.log',`RecoveryTool 3.1<br>2018-07-04 22:16<br><br>Recovered index: 3 files<br>External archive reference: D:\\BACKUP_OLD<br>Archive mode: read-only / local verification required<br><br>Hint field preserved: 回家那天`);
   if(type==='sicknote'){mark('shenyan_absence');return {title:'请假单_2012.jpg - Windows 图片和传真查看器',type:'photo-viewer',menubar:'',toolbar:'<div class="photo-tools"><button>上一张</button><button>下一张</button><button>放大</button><button>缩小</button><button>打印</button></div>',body:`<div class="document-photo"><div class="leave-slip"><div class="slip-school">鹤宁实验小学</div><h2>学生请假单</h2><div class="slip-row"><b>学生姓名</b><span>沈妍</span><b>班级</b><span>一年级二班</span></div><div class="slip-row"><b>请假时间</b><span>2012年10月2日至10月3日</span></div><div class="slip-row"><b>请假事由</b><span>发烧，在家休息</span></div><div class="slip-sign">家长签字：何惠</div><div class="slip-stamp">班主任已阅</div></div><div class="single-photo-caption">扫描来源：何惠遗物箱内纸本。背面无其他字迹。</div></div>`,status:'请假单_2012.jpg'};}
 if(type==='notice'){mark('shenyan_notice');return {title:'寻人启事_排版稿.doc - Microsoft Word',type:'word-viewer',menubar:'<div class="classic-menu">文件(F)　编辑(E)　视图(V)　插入(I)　格式(O)　工具(T)　表格(A)　窗口(W)　帮助(H)</div>',toolbar:'<div class="word-toolbar"><button>打开</button><button>保存</button><button>打印</button><span>宋体　小二　<b>B</b></span></div>',body:`<div class="word-workarea"><article class="word-page missing-notice"><h1>寻 人 启 事</h1><p>沈妍，女，6岁，身高约118cm。2012年10月2日下午在南关早市附近与家人走散，走失时穿浅灰外套、红色布鞋。</p><p>如有线索，请联系何女士。</p><p class="word-meta">文件创建：2012-10-02 19:42　打印记录：无</p></article></div>`,status:'第1页，共1页'};}
 if(type==='privateMemo')return notepad('调查备忘.txt',`我以前一直觉得妈只是迷信。她不让我养猫，亲戚叫我小名的时候她会突然打断，路过南关也宁愿多绕一站。<br><br>她跟学校说我六岁那两天只是发烧，可寻人启事是她自己排的版。既然我没丢，她为什么要写这个？<br><br>照片里她一直低头看着我。我以前只觉得她没看镜头，现在有点不敢再看。<br><br>还没核对：照片原图、妈留下的旧日历。`);
 if(type==='calendarLocal'){mark('calendar');return {title:'旧日历_2012_10.jpg - Windows 图片和传真查看器',type:'photo-viewer',menubar:'',toolbar:'<div class="photo-tools"><button>上一张</button><button>下一张</button><button>放大</button><button>缩小</button><button>打印</button></div>',body:`<div class="diary-photo"><div class="scan diary-scan"><b>何惠旧日历 · 2012年10月</b><p>10月2日　给学校打过电话，只说发烧。寻人启事已经排好了，先别往外贴。</p><p>10月3日　下午把她接回来。晚上一直不认床，说这不是她睡觉的屋。我陪她坐到后半夜，她也没哭。</p><p>10月4日　早上终于肯吃鸡蛋羹了。吃到一半，她问我以后还要不要送她回“原来住的地方”。我没问她说的是哪里。</p><p>10月5日　今天在厨房里叫了我一声妈。我本来想问这两天去了哪里，最后还是没问。</p><p>10月6日　已经跟老师说过了，这阵子先叫大名。下午把猫送给小妹，南关那边也先不去了。</p><p>这些事以后不记了。</p></div></div>`,status:'旧日历_2012_10.jpg'};}
 if(type==='scan1124'||type==='scan1125'||type==='scan1127')return image(type+'.tif','assets/old_street.jpg','旧报纸扫描缩略图。要检索OCR文字请打开“数字报刊.url”。');
 if(type==='driveC')return explorer('本地磁盘 (C:)','C:\\',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-open="syfolder"><img src="assets/icons/folder.png"><span>Documents and Settings</span></button><button class="explorer-file"><img src="assets/icons/folder.png"><span>Program Files</span></button><button class="explorer-file"><img src="assets/icons/folder.png"><span>WINDOWS</span></button></div>`,3);
 if(type==='driveD')return explorer('资料盘 (D:)','D:\\',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-open="private"><img src="assets/icons/lock.png"><span>BACKUP_OLD</span></button><button class="explorer-file" data-local="restorelog"><img src="assets/icons/tmp.png"><span>RECOVERY.LOG</span></button></div>`,2);
 if(type==='dvd')return {title:'DVD 驱动器 (E:)',type:'explorer',menubar:'',toolbar:'',body:'<div class="empty-drive"><b>请将光盘插入驱动器 E:。</b></div>',status:'0 个对象'};
 return notepad('文件','该文件没有可显示的内容。');
}
function photoHTML(){
 mark('photo_meta');
 return `<div class="photo-view-layout"><div class="photo-canvas"><div class="photo-frame"><img src="assets/mother_child_photo.jpg" alt="一张低清母女合影"></div></div><aside class="photo-note-panel"><div class="photo-note-title">照片信息</div><dl><dt>文件名</dt><dd>IMG_2002.jpg</dd><dt>拍摄日期</dt><dd>2012-10-04 10:18</dd><dt>备注</dt><dd class="hand-note">回来的第二天，<br>终于肯吃饭了。</dd></dl></aside></div><div class="photo-status-note">【家庭照片】人物眼部已做隐私遮挡。文件名后来改过，但相机日期和照片背面的手写备注一直保留着。</div>`;
}
function timelineHTML(){
 const canFinal=state.stage>=7;
 return `<div class="timeline-wrap"><div class="sheet-tabs-top"><span class="namebox">A1</span><span class="formula-input">事件时间线</span></div><table class="excel-grid"><thead><tr><th class="rowhead"></th><th>A</th><th>B</th><th>C</th><th>D</th><th>E</th></tr><tr><th class="rowhead">1</th><th>时间</th><th>事件</th><th>人物</th><th>证据来源</th><th>备注</th></tr></thead><tbody>
 <tr><th class="rowhead">2</th><td>1996.11.24</td><td>南关儿童一度失联</td><td>何惠</td><td>晚报 / 学校</td><td>口径不一致</td></tr>
 <tr><th class="rowhead">3</th><td>1996.11.27</td><td>何惠返校</td><td>何惠</td><td>班主任记录</td><td>称呼异常</td></tr>
 <tr><th class="rowhead">4</th><td>1996.11.29</td><td>办理转学</td><td>何惠</td><td>学校档案</td><td>迅速切断旧关系</td></tr>
 <tr><th class="rowhead">5</th><td>2012.10.02</td><td>南关早市走散</td><td>沈妍</td><td>寻人稿</td><td>未打印</td></tr>
 <tr><th class="rowhead">6</th><td>2012.10.03</td><td>旧二路终点附近被找到</td><td>沈妍</td><td>邻居旧帖</td><td>约30余小时</td></tr>
 <tr><th class="rowhead">7</th><td>${has('final_date')?'2012.10.04':canFinal?'<input id="finalDate" inputmode="numeric" placeholder="YYYY-MM-DD">':'（待核）'}</td><td>母女合影</td><td>沈妍 / 何惠</td><td>照片 EXIF / 背面</td><td>${has('final_date')?'<b>第二天</b>':'—'}</td></tr>
 </tbody></table><div class="sheet-bottom-tabs"><span class="active">事件时间线</span><span>资料来源</span><span>其他线索</span></div>
 ${canFinal&&!has('final_date')?'<div class="excel-actionbar"><button id="finalSubmit">写入日期</button><span id="finalMsg">按照片原始信息填写，格式 YYYY-MM-DD。</span></div>':''}
 ${has('final_date')?`<div class="final-file-row"><span class="final-file-label">附件</span><button id="finalPhoto" class="final-photo-link"><img src="assets/mother_child_photo.jpg" alt="照片缩略图"><span>IMG_2002.jpg</span></button></div>`:''}
 ${has('final_photo')?'<div class="photo-back"><div class="photo-back-label">照片背面</div><div class="photo-back-hand">回来的第二天，终于肯吃饭了。</div></div><div class="caption">工作簿里没有别的附件了。</div>':''}</div>`;
}
function privateLoginHTML(){
 if(has('private_notes')) return `<div class="backup-open"><div class="backup-banner"><b>旧电脑备份</b><span>归档日期：2018-07-04　只读</span></div><div class="explorer-icon-grid rich compact-files backup-files"><button class="explorer-file" data-local="privateMemo"><img src="assets/icons/tmp.png"><span>调查备忘.txt</span></button><button class="explorer-file" data-local="calendarLocal"><img src="assets/icons/imagefile.png"><span>旧日历_2012_10.jpg</span></button><button class="explorer-file" data-open="photo"><img src="assets/icons/photo.png"><span>IMG_2002.jpg</span></button><button class="explorer-file" data-open="timeline"><img src="assets/icons/sheet.png"><span>调查记录.xls</span></button></div><div class="backup-note">这个备份不是完整硬盘镜像，只保留了沈妍手动归档的四个文件。</div></div>`;
 return `<div class="private-screen"><div class="login classic-login"><div class="login-title">旧电脑备份</div><p>该目录使用旧版本地加密工具保护。需要账户名和校验信息才能读取。</p><label>账户名<input id="loginUser" autocomplete="off"></label><label>校验日期 <span>备份程序只留下了提示："回家那天"</span><input id="loginPass" inputmode="numeric" autocomplete="off" placeholder="YYYYMMDD"></label><button id="loginSubmit">确定</button><button class="classic-button" data-open="syfolder">取消</button><div id="loginMsg" class="login-message"></div></div></div>`;
}



function workHTML(){return xpExplorerLayout('文件和文件夹任务','<button class="static-task">新建文件夹</button><button class="static-task">按名称排列</button>',`<div class="details-list"><div class="details-head"><span>名称</span><span>类型</span><span>修改日期</span><span>大小</span></div>${[['会议纪要_0407.doc','Microsoft Word 文档','2026-09-07','84 KB'],['报销单_三月.xls','Microsoft Excel 工作表','2026-09-03','31 KB'],['周报_14.doc','Microsoft Word 文档','2026-09-01','56 KB'],['客户资料','文件夹','2026-08-29',''],['素材待确认','文件夹','2026-08-25',''],['logo_old.ai','Adobe Illustrator 文件','2026-08-18','2.1 MB'],['readme.txt','文本文档','2026-07-11','2 KB']].map(x=>`<div class="details-row"><span><img src="assets/icons/${x[1]==='文件夹'?'folder':'doc'}.png">${x[0]}</span><span>${x[1]}</span><span>${x[2]}</span><span>${x[3]}</span></div>`).join('')}</div>`)}
function travelHTML(){return xpExplorerLayout('图片任务','<button class="static-task">以幻灯片方式查看</button><button class="static-task">打印图片</button>',`<div class="details-list"><div class="details-head"><span>名称</span><span>拍摄日期</span><span>大小</span><span>备注</span></div>${[['IMG_1732.jpg','2025-10-03','1.8 MB','火车站'],['IMG_1741.jpg','2025-10-03','2.0 MB','江边'],['IMG_1818.jpg','2025-10-04','1.6 MB','早餐店'],['IMG_1902.jpg','2025-10-05','2.3 MB','山路'],['IMG_1930.jpg','2025-10-05','1.9 MB','返程'],['路线.txt','2025-09-29','1 KB',''],['车票截图.png','2025-09-28','436 KB','']].map(x=>`<div class="details-row"><span><img src="assets/icons/${x[0].endsWith('.txt')?'doc':'imagefile'}.png">${x[0]}</span><span>${x[1]}</span><span>${x[2]}</span><span>${x[3]}</span></div>`).join('')}</div>`)}
function downloadsHTML(){return xpExplorerLayout('文件和文件夹任务','<button class="static-task">删除所选项目</button><button class="static-task">按类型排列</button>',`<div class="details-list"><div class="details-head"><span>名称</span><span>类型</span><span>修改日期</span><span>大小</span></div>${[['FlashPlayer10.exe','应用程序','2025-08-11','2.7 MB'],['公交线路图.pdf','PDF 文档','2026-08-30','1.1 MB'],['hn2ps_old.zip','WinRAR 压缩文件','2026-08-18','6.4 MB'],['QQ截图20230402.bmp','位图图像','2023-04-02','912 KB'],['字体包.zip','WinRAR 压缩文件','2025-12-10','8.7 MB'],['readme(1).txt','文本文档','2025-09-17','3 KB']].map(x=>`<div class="details-row"><span><img src="assets/icons/${x[0].endsWith('.zip')?'zip':x[0].endsWith('.txt')?'doc':'misc'}.png">${x[0]}</span><span>${x[1]}</span><span>${x[2]}</span><span>${x[3]}</span></div>`).join('')}</div>`)}
function controlHTML(){
 const items=[['computer','显示','桌面、屏幕保护程序和外观'],['browser','网络连接','宽带和本地连接'],['cd','添加或删除程序','安装或卸载软件'],['photo','用户账户','沈妍'],['tmp','日期和时间','2026年9月13日'],['media','声音和音频设备','扬声器 / 系统声音'],['folder','文件夹选项','常规、查看、文件类型'],['doc','打印机和传真','无已安装打印机']];
 return `<div class="control-grid">${items.map((x,i)=>`<button class="control-item" data-control="${i}"><img class="control-img" src="assets/icons/${x[0]}.png" alt=""><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div><div id="controlPreview" class="control-preview">选择一个控制面板项目查看设置。</div>`
}
function systemInfoHTML(){return `<div class="sysprop"><div class="sys-logo">Windows XP</div><p><b>Microsoft Windows XP Professional</b><br>版本 2002　Service Pack 3</p><hr><p>注册到：沈妍<br>计算机：Intel Pentium Dual-Core<br>1.96 GB 内存</p><p class="muted">部分硬件信息暂不可用。要查看设备状态，请打开“设备管理器”。</p></div>`}
function helpHTML(){return `<div class="help-layout"><aside><b>帮助主题</b><button>Windows 基础</button><button>文件和文件夹</button><button>网络和 Internet</button><button>照片和图片</button></aside><main><h2>帮助和支持中心</h2><p>选择左侧主题，或在开始菜单中使用“搜索”查找文件。</p><div class="help-tip"><b>提示</b><br>要打开桌面项目，请双击图标；要选择项目，请单击一次。</div></main></div>`}
function searchHTML(){return `<div class="search-dog"><div class="search-pane"><h3>您要查找什么？</h3><label>全部或部分文件名：<input id="localSearchKw" placeholder="例如：1996 / 何惠 / 照片"></label><button id="localSearchBtn" class="classic-button">搜索</button></div><div id="searchResults" class="search-results"><p>在本地磁盘和“我的文档”中搜索。</p></div></div>`}
function runHTML(){return `<div class="run-box"><p>请输入程序、文件夹、文档或 Internet 资源的名称，Windows 将为您打开它。</p><label>打开(O)：<input id="runInput" value=""></label><div><button id="runOk" class="classic-button">确定</button><button id="runCancel" class="classic-button">取消</button></div><div id="runMsg" class="muted"></div></div>`}
function qqHTML(){return `<div class="qq-login"><img src="assets/icons/qq.png" alt=""><h3>腾讯QQ 2009</h3><label>号码 <input value="42790618" readonly></label><label>状态 <select><option>离线</option></select></label><button id="qqLogin" class="classic-button">登录</button><p id="qqMsg" class="muted">上次登录：2026-09-11 22:18</p></div>`}
function mediaHTML(){return `<div class="wmp"><div class="wmp-screen"><div class="wmp-logo">Windows Media Player</div><div id="wmpTrack" class="wmp-track">未播放</div></div><div class="wmp-controls"><button data-media="prev">◀◀</button><button data-media="play">▶</button><button data-media="stop">■</button><button data-media="next">▶▶</button><span id="wmpTime">00:00 / 00:00</span></div><div class="playlist"><b>播放列表</b><button class="playlist-row" data-track="周末电台剪辑.wma">01　周末电台剪辑.wma</button><button class="playlist-row" data-track="录音_空白.wav">02　录音_空白.wav</button><button class="playlist-row" data-track="系统提示音.wav">03　系统提示音.wav</button></div></div>`}
function zipHTML(){return `<div class="zip-toolbar"><button>添加</button><button>解压到</button><button>测试</button><button>查看</button><button>删除</button></div><div class="details-list"><div class="details-head"><span>名称</span><span>大小</span><span>修改日期</span><span>CRC32</span></div>${[['IMG_1997.jpg','732 KB','2018-07-04','A1E83B2C'],['IMG_1998.jpg','818 KB','2018-07-04','920AB8D1'],['IMG_2001.jpg','694 KB','2018-07-04','33C9FA08'],['IMG_2002.jpg','847 KB','2018-07-04','81D3A9C2'],['IMG_2003.jpg','761 KB','2018-07-04','D10684B2'],['IMG_2004.jpg','802 KB','2018-07-04','BC77E21A'],['说明.txt','1 KB','2018-07-04','02D2140F']].map(x=>`<div class="details-row"><span>${x[0]}</span><span>${x[1]}</span><span>${x[2]}</span><span>${x[3]}</span></div>`).join('')}</div>`}
function bindLocal(){
 bindWindow();
 document.querySelectorAll('[data-local]').forEach(b=>b.onclick=()=>openLocal(b.dataset.local)); document.querySelectorAll('[data-web]').forEach(b=>b.onclick=()=>openBrowser(b.dataset.web)); document.querySelectorAll('[data-cache]').forEach(b=>b.onclick=()=>triggerBlackout());
 const statusMsg=(m)=>{const st=document.querySelector('.window-status');if(st)st.textContent=m};
 document.querySelectorAll('.static-task').forEach(b=>b.onclick=()=>{b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),120);const t=b.textContent.trim();if(t.includes('新建'))statusMsg('该目录为只读备份，无法新建文件夹。');else if(t.includes('排列'))statusMsg('项目已按'+t.replace('排列','')+'排列。');else if(t.includes('清空')||t.includes('还原'))statusMsg('当前账户没有修改回收站的权限。');else if(t.includes('幻灯片'))statusMsg('此目录仅保存资料图，幻灯片功能不可用。');else if(t.includes('打印'))statusMsg('未检测到可用打印机。');else statusMsg('操作完成。')});
 document.querySelectorAll('.xp-tool,.xp-go').forEach(b=>b.onclick=()=>{b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),120);const t=b.textContent.trim();if(t.includes('搜索')){openWin('search');return}if(t.includes('文件夹')){const tree=document.querySelector('.explorer-tree');if(tree){tree.classList.toggle('tree-hidden');statusMsg(tree.classList.contains('tree-hidden')?'文件夹侧栏已隐藏。':'文件夹侧栏已显示。')}return}if(t==='↑'){statusMsg('已经位于当前归档的最高可浏览层级。');return}if(t==='←'||t==='→'){statusMsg('没有可用的文件夹浏览历史。');return}statusMsg('当前位置已打开。')});
 document.querySelectorAll('.word-toolbar button,.excel-ribbon button').forEach(b=>b.onclick=()=>{b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),120);statusMsg(/打印/.test(b.textContent)?'未检测到可用打印机。':'该文件以只读方式打开。')});
 document.querySelectorAll('.photo-tools button').forEach(b=>b.onclick=()=>{b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),120);const img=document.querySelector('.photo-viewer .window-body img');const t=b.textContent.trim();if(!img){statusMsg('没有可操作的图像。');return}let z=Number(img.dataset.zoom||1),r=Number(img.dataset.rotate||0);if(t.includes('放大'))z=Math.min(2,z+.15);else if(t.includes('缩小'))z=Math.max(.55,z-.15);else if(t.includes('左转'))r-=90;else if(t.includes('右转'))r+=90;else if(t.includes('打印')){statusMsg('未检测到可用打印机。');return}else if(t.includes('上一张')||t.includes('下一张')){statusMsg('当前查看器只打开了这一张图像。');return}else if(t.includes('保存')){statusMsg('该图像已经保存在本地。');return}img.dataset.zoom=z;img.dataset.rotate=r;img.style.transform=`scale(${z}) rotate(${r}deg)`;statusMsg(`缩放 ${Math.round(z*100)}%　旋转 ${((r%360)+360)%360}°`)});
 document.querySelectorAll('.wmp-controls button,.zip-toolbar button').forEach(b=>b.onclick=()=>{b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),120)});
 document.querySelectorAll('[data-control]').forEach(b=>b.onclick=()=>{const p=document.getElementById('controlPreview');if(p)p.innerHTML='<b>'+b.querySelector('b').textContent+'</b><p>'+b.querySelector('small').textContent+'</p><p class="muted">当前账户权限有限；部分设置需要管理员权限才能保存。</p>'});
 const lsb=document.getElementById('localSearchBtn');if(lsb)lsb.onclick=()=>{const q=(document.getElementById('localSearchKw').value||'').trim();const r=document.getElementById('searchResults');const pool=['1996资料\\剪报索引_1996.txt','1996资料\\户籍摘录_何惠.txt','照片\\IMG_2002.jpg','未整理\\论坛用户名.txt','沈妍的资料\\调查记录.xls','沈妍的资料\\毕业论文.doc'];const hit=pool.filter(x=>!q||x.includes(q));r.innerHTML=hit.length?hit.map(x=>'<div class="search-hit">'+esc(x)+'</div>').join(''):'<p>搜索完成。没有找到文件。</p>';};
 const rok=document.getElementById('runOk');if(rok)rok.onclick=()=>{const v=(document.getElementById('runInput').value||'').trim().toLowerCase();if(v==='notepad'||v==='notepad.exe')openWin('doc');else if(v==='iexplore'||v==='iexplore.exe')openWin('browser');else if(v==='calc'||v==='calc.exe')document.getElementById('runMsg').textContent='Windows 找不到 calc.exe。文件可能已被移动或删除。';else document.getElementById('runMsg').textContent='Windows 找不到“'+v+'”。请检查名称后重试。';}; document.getElementById('runCancel')?.addEventListener('click',closeWin);
 const ql=document.getElementById('qqLogin');if(ql)ql.onclick=()=>{document.getElementById('qqMsg').textContent='连接服务器超时。请检查网络连接后重试。';};
 document.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>{const t=document.getElementById('wmpTrack');const tm=document.getElementById('wmpTime');if(t)t.textContent=b.dataset.track+'　（无法找到媒体文件）';if(tm)tm.textContent='00:00 / 00:00';});
 document.querySelectorAll('[data-media]').forEach(b=>b.onclick=()=>{const t=document.getElementById('wmpTrack');if(!t)return;if(b.dataset.media==='stop')t.textContent='已停止';else if(b.dataset.media==='play')t.textContent='无法播放：媒体文件路径已失效';});
 const fs=document.getElementById('finalSubmit'); if(fs)fs.onclick=()=>{const v=document.getElementById('finalDate').value.trim().replace(/[/.]/g,'-');if(v==='2012-10-04'||v==='20121004'){mark('final_date');win='timeline';render()}else document.getElementById('finalMsg').textContent='日期与原图信息对不上。'}; const fp=document.getElementById('finalPhoto'); if(fp)fp.onclick=()=>{mark('final_photo');win='timeline';render()};
 const ls=document.getElementById('loginSubmit'); if(ls)ls.onclick=()=>{const u=document.getElementById('loginUser').value.trim().toLowerCase();const p=document.getElementById('loginPass').value.trim();if((u==='sy0718'||u==='sheny0718'||u==='shenyan0718')&&p==='20121003'){mark('private_notes');win='private';render()}else document.getElementById('loginMsg').textContent='账号或校验日期不匹配。'};
}

function siteBase(r){const b=(r||'home').split(':')[0];if(b==='police'||b.startsWith('news'))return'news';if(b==='teacher'||b.startsWith('school'))return'school';if(b==='thread'||b.startsWith('forum'))return'forum';if(b.startsWith('culture'))return'culture';if(b==='libdoc'||b.startsWith('library'))return'library';return b}
function siteLabel(b){return ({home:'空白页',news:'鹤宁晚报',school:'鹤宁二小',forum:'南关人家',culture:'地方文化馆',library:'市图书馆'}[b]||b)}
function openBrowser(route,push=true){browserRoute=route||'home';win='browser';minimizedWin=null;const base=siteBase(browserRoute);if(['news','school','forum','culture','library'].includes(base)&&!browserTabs.includes(base))browserTabs.push(base);if(push){historyStack=historyStack.slice(0,historyIndex+1);historyStack.push(browserRoute);historyIndex=historyStack.length-1}renderBrowserShell()}
function nav(route){openBrowser(route,true)}
function renderBrowserShell(){
 const bb=browserRoute.split(':')[0]; const title=bb==='home'?'Microsoft Internet Explorer':bb==='offline'?'无法显示网页':bb.startsWith('news')||bb==='police'?'鹤宁晚报数字报刊':bb.startsWith('school')||bb==='teacher'?'鹤宁市第二小学':bb.startsWith('forum')||bb==='thread'?'南关人家 - 论坛':bb.startsWith('culture')?'鹤宁地方文化馆':bb.startsWith('library')||bb==='libdoc'?'鹤宁市图书馆':'网页';
 app.innerHTML=desktopHTML()+`<section class="browser-window ${winMax?'maximized':''}">
 <div class="browser-titlebar"><img src="assets/icons/browser.png" alt=""><strong>${esc(title)} - Microsoft Internet Explorer</strong><div class="browser-window-controls"><button id="browserMin">_</button><button id="browserMax">□</button><button id="browserClose">×</button></div></div><div class="ie-tabs">${browserTabs.map(t=>`<button class="ie-tab ${siteBase(browserRoute)===t?'active':''}" data-tab="${t}">${siteLabel(t)}</button>`).join('')}</div>
 <div class="browser-menubar">文件(F)　编辑(E)　查看(V)　收藏(A)　工具(T)　帮助(H)</div>
 <div class="ie-toolbar"><button class="ie-tool" id="backBtn" ${historyIndex<=0?'disabled':''}>◀<small>后退</small></button><button class="ie-tool" id="fwdBtn" ${historyIndex>=historyStack.length-1?'disabled':''}>▶<small>前进</small></button><span class="ie-sep"></span><span class="ie-tool static">■<small>停止</small></span><span class="ie-tool static">↻<small>刷新</small></span><span class="ie-tool static">⌂<small>主页</small></span><span class="ie-sep"></span><span class="ie-tool static">⌕<small>搜索</small></span><span class="ie-tool static">★<small>收藏夹</small></span></div>
 <div class="browser-top"><span class="address-label">地址(D)</span><input id="address" class="address" value="http://${esc(routeUrl(browserRoute))}"><button id="goBtn" class="go">转到</button></div>
 <div class="bookmarkbar"><span class="fav-label">收藏夹</span>${browserTabs.map(t=>`<button data-nav="${t}">${siteLabel(t)}</button>`).join('')}</div>
 <div id="browserContent" class="browser-content">${renderRoute(browserRoute)}</div><div class="browser-status"><span>完成</span><span>本地缓存：可用　脱机工作</span><span>Internet</span></div></section>`;
 bindBrowser();renderAnchor();
}
function routeUrl(r){const base=r.split(':')[0];if(base==='home')return'about:blank';if(base==='offline')return decodeURIComponent(r.slice(8));if(base==='police')return'archive.heningdaily.local/attachment/ng-police-1996';if(base.startsWith('news'))return'archive.heningdaily.local/'+(base==='news'?'':'view/'+encodeURIComponent(r.split(':')[1]||'search'));if(base.startsWith('school')||base==='teacher')return'old.hn2ps.edu.local/'+(base==='school'?'':'archive/'+base);if(base.startsWith('forum')||base==='thread')return'bbs.nanguan.local/'+(base==='forum'?'':'thread/'+(r.split(':')[1]||'search'));if(base.startsWith('culture'))return'culture.hening.local/'+(base==='culture'?'':'data/'+(r.split(':')[1]||'search'));if(base.startsWith('library')||base==='libdoc')return'lib.hening.local/'+(base==='library'?'':'local/'+(r.split(':')[1]||'search'));return'local/'+r}
function fromAddress(v){const raw=v.trim();const x=raw.toLowerCase().replace(/^https?:\/\//,'').replace(/\/$/,'');if(!raw||x==='about:blank')return'home';if(x.startsWith('archive.heningdaily.local'))return'news';if(x.startsWith('old.hn2ps.edu.local'))return'school';if(x.startsWith('bbs.nanguan.local'))return'forum';if(x.startsWith('culture.hening.local'))return'culture';if(x.startsWith('lib.hening.local'))return'library';return'offline:'+encodeURIComponent(raw)}
function bindBrowser(){
 document.getElementById('browserClose').onclick=()=>{win=null;winMax=false;render()};
 document.getElementById('browserMin').onclick=()=>{minimizedWin='browser';win=null;render()};
 document.getElementById('browserMax').onclick=()=>{winMax=!winMax;renderBrowserShell()};
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>nav(b.dataset.tab));
 const at=document.getElementById('anchorToggle'); if(at)at.onclick=()=>{anchorOpen=!anchorOpen;renderAnchor()}; document.getElementById('anchorClose')?.addEventListener('click',()=>{anchorOpen=false;renderAnchor()});
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));
 document.getElementById('goBtn').onclick=()=>nav(fromAddress(document.getElementById('address').value));
 document.getElementById('address').onkeydown=e=>{if(e.key==='Enter')nav(fromAddress(e.currentTarget.value))};
 document.getElementById('backBtn').onclick=()=>{if(historyIndex>0){historyIndex--;browserRoute=historyStack[historyIndex];renderBrowserShell()}};
 document.getElementById('fwdBtn').onclick=()=>{if(historyIndex<historyStack.length-1){historyIndex++;browserRoute=historyStack[historyIndex];renderBrowserShell()}};
 bindRoute(browserRoute);
}
function renderRoute(r){
 const [base,arg]=r.split(':');
 if(base==='home') return browserHome(); if(base==='offline') return browserOffline(decodeURIComponent(r.slice(8)));
 if(base==='news') return newsHome(); if(base==='newsarticle') return newsArticle(arg); if(base==='newssearch') return newsSearch(arg);
 if(base==='police') return policeDoc();
 if(base==='school') return schoolHome(); if(base==='schoolarchive') return schoolArchive(); if(base==='schoolstudent') return schoolStudent(); if(base==='teacher') return teacherRecord(); if(base==='schoolnotice') return schoolNotice(arg);
 if(base==='forum') return forumHome(); if(base==='forumsearch') return forumSearch(arg); if(base==='thread') return forumThread(arg);
 if(base==='culture') return cultureHome(); if(base==='culturesearch') return cultureSearch(arg); if(base==='culturearticle') return cultureArticle(arg);
 if(base==='library') return libraryHome(); if(base==='librarysearch') return librarySearch(arg); if(base==='libdoc') return libraryDoc(arg);
 return newsHome();
}
function siteHeader(type,title){return `<div class="${type}">`}
function browserHome(){return `<div class="ie-home"><div class="ie-home-logo">Microsoft Internet Explorer</div><h2>脱机工作</h2><p>这台电脑没有连接互联网。你仍然可以打开已经缓存的网页，或在地址栏输入保存过的网址。</p><p class="muted">脱机模式下，只有保存在此计算机上的页面能够正常打开。</p></div>`}
function browserOffline(v){return `<div class="ie-error"><h2>无法显示网页</h2><p>Internet Explorer 无法打开 <b>${esc(v)}</b>。</p><hr><p>请检查地址是否正确，或确认该网页曾被保存到本地缓存。</p></div>`}
function newsHome(){return `<div class="site news"><div class="mast"><div class="brand">鹤宁晚报</div><div class="mast-meta">HENING EVENING NEWS</div><div class="issue-date">1996年12月3日　星期二<br><span>农历丙子年十月廿三</span></div><div class="news-quick-search"><input id="newsKw" placeholder="站内搜索"><button id="newsSearch" class="action">搜索</button></div></div><div class="subnav"><span>首页</span><span>本地新闻</span><span>社会</span><span>民生</span><span>文体</span><span>副刊</span><span>数字报刊</span><span>旧版检索</span></div><div class="wrap"><div class="newspaper-front"><section><h2>历史报刊检索</h2><div class="news-searchbox"><div class="search-row"><label>起始日期<input id="newsFrom" value="1996-11-20" placeholder="YYYY-MM-DD"></label><label>结束日期<input id="newsTo" value="1996-11-30" placeholder="YYYY-MM-DD"></label><button class="action" id="newsSearch2">检索</button></div><div class="archive-stat">馆藏 21,842 期 · 1990—2002 年版面已完成 OCR · 原版扫描可能存在污损和错字</div></div><h3 class="paper-section-title">1996 年 11 月整理批次</h3>${normalNews.slice(0,10).map(n=>`<div class="news-row"><div class="date">${n[0]}</div><div><button class="linklike" data-news="${n[0]}">${n[1]}</button><div class="muted">${n[2]} · 历史版面</div></div></div>`).join('')}</section><aside class="news-front-side"><img src="assets/old_street.jpg" alt="南关旧街"><div class="news-caption">图：南关街旧照（资料图）</div><h4>本期其他新闻</h4><p>我市开展冬季校园安全检查工作</p><p>南关片区加强夜间巡逻</p><p>供暖公司回应市民关闭问题</p></aside></div></div></div>`}
function newsSearch(q=''){const raw=decodeURIComponent(q||'');const [kw0,from='',to='']=raw.split('|');const kw=kw0.trim();let rows=normalNews.filter(n=>!kw||n.join(' ').includes(kw)||(/南关|儿童|老人|猫脸|兰兰/.test(kw)&&/南关|儿童|怪老人/.test(n[1])));if(from)rows=rows.filter(n=>n[0]>=from);if(to)rows=rows.filter(n=>n[0]<=to);return `<div class="site news"><div class="mast"><div class="brand">鹤宁晚报</div><div>数字报刊资料库</div></div><div class="subnav"><span>旧报检索</span><span>版面浏览</span><span>馆藏说明</span></div><div class="wrap"><p><button class="linklike" data-nav="news">← 修改检索条件</button></p><h2>检索结果：${esc(kw)}</h2><div class="muted" style="margin:-10px 0 18px">${from||'不限'} 至 ${to||'不限'} · ${rows.length} 条结果</div><div class="news-list">${rows.map(n=>`<div class="news-row"><div class="date">${n[0]}</div><div><button class="linklike" data-news="${n[0]}">${n[1]}</button><div class="muted">${n[2]} · 第 3 版 · 版面扫描</div></div></div>`).join('')||'<p class="muted">没有匹配结果。</p>'}</div></div></div>`}
function newsArticle(date){
 const common=`<div class="site news"><div class="mast"><div class="brand">鹤宁晚报</div><div class="mast-meta">HENING EVENING NEWS</div><div class="issue-date">历史数字报刊</div></div><div class="subnav"><span>首页</span><span>本地新闻</span><span>社会</span><span>民生</span><span>文体</span><span>副刊</span><span>数字报刊</span><span>旧版检索</span></div><div class="wrap article"><div class="article-crumb">数字报刊 &gt; 1996年11月</div><button class="linklike" data-nav="news">← 返回数字报刊</button>`;
 if(date==='1996-11-24'){mark('news5');return common+`<h1 class="headline">南关五名儿童一度与家长失去联系</h1><div class="muted">1996-11-24 · 社会版</div><p>本报讯　昨日傍晚，南关一带有五名低龄儿童在放学、买菜及外出途中一度与家长失去联系。家属、学校和辖区民警连夜寻找，截至今晨已有两名儿童由家属自行接回，其余情况仍在核实。</p><p>鹤宁第二小学表示，学校当日正常上课，但有多名学生因病、家庭原因或去向不明未到校。校方已临时要求低年级学生放学后由家长接送。</p><p>近日附近关于“怪老人夜间找孩子”的说法较多，警方提醒居民不要把未经证实的传言与儿童走失情况混在一起。</p><div class="archive-source-box"><b>数字化关联资料</b><span>校方当日缺勤数字可在学校旧站的校史附件中核对。</span><button class="linklike" data-nav="school">鹤宁第二小学旧官网镜像</button></div><p>相关：<button class="linklike" data-news="1996-11-25">关于南关“怪老人”传言的情况说明</button></p></div></div>`}
 if(date==='1996-11-25')return common+`<h1 class="headline">关于南关“怪老人”传言的情况说明</h1><div class="muted">1996-11-25 · 社会版</div><p>南关街道办昨日表示，近期所谓“猫脸老人抓孩子”等说法与已掌握事实不符。居民确曾反映一名面部有旧疾的老妇人在夜间沿街寻找儿童，询问内容多为“有没有见过兰兰”。</p><p>记者核实，该老妇赵淑琴的外孙女冯小兰于 11 月 23 日傍晚走失。赵某于次日清晨突发疾病去世。</p><p>街道工作人员呼吁不要将老人外貌与儿童失联事件混为一谈。</p><div style="display:flex;gap:16px;align-items:flex-start;flex-wrap:wrap"><img src="assets/zhao_newsprint_photo.jpg" alt="旧报纸中的赵淑琴照片" style="width:145px;border:1px solid #777;background:#ddd;padding:3px"><div class="muted" style="max-width:420px">【报刊资料图】赵淑琴旧照。人物眼部已做隐私遮挡；原报扫描网点严重，右半脸有重影和折痕。</div></div></div></div>`;
 if(date==='1996-11-27')return common+`<h1 class="headline">南关多名儿童已与家属取得联系</h1><div class="muted">1996-11-27 · 社会版</div><p>截至昨晚，此前一度与家长失去联系的儿童已有四人与家属团聚，另有一名仍在寻找。辖区民警表示，部分家属在正式报案前已自行找到孩子，因此公开案号数量与早期媒体统计并不完全一致。</p><p>警方后续公开材料可见：<button class="linklike" data-nav="police">南关辖区 1996 年 11 月接处警摘要</button>。</p></div></div>`;
 {const n=normalNews.find(n=>n[0]===date);const ordinary={
 '1996-11-29':'本报讯　市公交公司自本周起增开冬季早班车，首班时间提前二十分钟。线路调整表已张贴于主要站点。',
 '1996-11-28':'本报讯　鹤宁纺织厂锅炉改造工程昨日完成试运行。厂方表示，冬季供热期间将继续安排夜间值守。',
 '1996-11-23':'本报讯　冬储白菜昨日进入集中上市期，南关、东河两处临时售卖点延长营业至晚七时。',
 '1996-11-22':'本报讯　青年宫乒乓球馆本周末恢复开放，上午面向学生，下午为职工活动时段。',
 '1996-11-21':'气象台预计本周末迎来今冬首场降雪，夜间最低气温可能降至零下六度。',
 '1996-11-20':'市环卫处将冬季清扫时间提前至清晨五时三十分，重点路段增加人工除冰班次。'};return common+`<h1 class="headline">${esc(n?.[1]||'历史报道')}</h1><div class="muted">${esc(date)} · ${esc(n?.[2]||'本地')}</div><p>${ordinary[date]||'本报讯　该版面为地方新闻存档，原件由市图书馆报刊库提供数字镜像。'}</p><p class="muted">版面号：${date.replace(/-/g,'')}-03　OCR 校对状态：已完成</p></div></div>`}
}
function policeDoc(){mark('police4');return `<div class="site library"><div class="head"><div class="libname">鹤宁市公开资料镜像</div></div><div class="wrap"><div class="doc-view"><div style="text-align:center"><h2>南关辖区 1996 年 11 月接处警摘要</h2><div class="muted">公开摘录 / 后期数字化</div></div><table class="school-table" style="margin-top:24px"><tr><th>日期</th><th>编号</th><th>事项</th><th>结果</th></tr><tr><td>11/23</td><td>NG961123-07</td><td>儿童走失</td><td>转失踪登记</td></tr><tr><td>11/23</td><td>NG961123-11</td><td>儿童走失</td><td>次日家属带回</td></tr><tr><td>11/24</td><td>NG961124-02</td><td>儿童走失</td><td>转失踪登记</td></tr><tr><td>11/24</td><td>NG961124-04</td><td>儿童走失</td><td>继续查找</td></tr><tr><td>11/24</td><td>口头求助</td><td>何姓家属称女童未归</td><td><b>家属后电话称已找到，未生成正式案号</b></td></tr></table><p class="muted" style="margin-top:14px">说明：口头求助未生成案号，后续只保留在值班摘要中。</p></div></div></div>`}

function schoolHome(){return `<div class="site school"><div class="header"><div class="head-inner"><div class="school-seal">鹤<br>二</div><div class="school-name-wrap"><div class="school-name">鹤宁市第二小学</div><div class="school-en">HENING NO.2 PRIMARY SCHOOL</div></div><div class="school-slogan"><b>团结　勤学　健康　快乐</b></div></div></div><div class="school-topnav"><span>学校首页</span><span>学校概况</span><span>校园新闻</span><span>通知公告</span><span>教学教研</span><span>德育天地</span><span>教师园地</span><span>学生天地</span><span>旧版资料</span></div><div class="wrap"><div class="school-grid"><aside class="leftmenu"><div>学校首页</div><div>学校概况</div><div>校园新闻</div><div>教务管理</div><div>德育天地</div><div>教师园地</div><div>学生作品</div><div><button class="linklike" data-nav="schoolarchive">旧版资料</button></div><div>联系我们</div></aside><section class="school-content"><div class="school-welcome"><div><h2>通知公告</h2><div class="ordinary-list">${schoolNotices.slice(0,8).map((x,i)=>`<div><span class="date">${x[0]}</span><button class="linklike" data-schoolnotice="${i}">· ${x[1]}</button></div>`).join('')}</div></div><aside><img src="assets/school_old.jpg" alt="学校旧照"><p>校舍旧照（网站资料图）<br>拍摄年代约2000年代初</p></aside></div><div class="school-bottom-strip"><span>校务公开</span><span>家校交流</span><span>卫生保健</span><span>少先队</span><span>资料下载</span></div></section></div><div class="old-counter">您是本站第 <b>0</b><b>3</b><b>2</b><b>6</b><b>1</b><b>7</b> 位访问者　　建议使用 IE6 / 1024×768 浏览</div></div></div>`}
function schoolNotice(i){i=Number(i);const x=schoolNotices[i]||schoolNotices[0];const bodies={0:'暑假前学校将对教学楼电路、消防器材和门窗进行集中检查，请各班离校前关闭电源并清空讲台杂物。值班教师名单另行下发。',1:'新学期9月1日正式上课。请班主任提前一天到校领取点名册和卫生工具，低年级家长接送区仍设在南门外。',2:'近期气温变化较大，校医室提醒家长注意流感和水痘预防。学生出现发热、皮疹等情况请在家休息并及时与班主任联系。',3:'本周三下午学校组织消防疏散演练，演练期间南侧楼梯临时封闭。请各班按广播顺序下楼，不得奔跑。',4:'第十七届田径运动会已结束，团体总分及单项成绩张贴在体育组门口，获奖证书下周一由班主任统一领取。',5:'经年级组推荐和学校评议，本年度优秀教师名单已公示。如有异议，请在三日内向校长室反映。',6:'本周五下午各班到操场东侧参加植树活动，学生自备手套，工具由总务处统一发放。',7:'学校正在整理历届毕业照、校刊和教师工作记录。如家中保存有1990年代学校资料，可送交校史办公室登记后扫描归还。'};return `<div class="site school"><div class="header"><div class="head-inner"><div class="school-seal">鹤<br>二</div><div class="school-name-wrap"><div class="school-name">鹤宁市第二小学</div><div class="school-en">HENING NO.2 PRIMARY SCHOOL</div></div><div class="school-slogan"><b>团结　勤学　健康　快乐</b></div></div></div><div class="school-topnav"><span>学校首页</span><span>学校概况</span><span>校园新闻</span><span>通知公告</span><span>教学教研</span><span>德育天地</span><span>教师园地</span><span>旧版资料</span></div><div class="wrap"><div class="school-grid"><aside class="leftmenu"><div><button class="linklike" data-nav="school">学校首页</button></div><div>校园新闻</div><div class="active-old">通知公告</div><div>教务管理</div><div><button class="linklike" data-nav="schoolarchive">旧版资料</button></div><div>联系我们</div></aside><section class="school-content old-article"><div class="crumb">学校首页 &gt; 通知公告 &gt; 正文</div><h1>${esc(x[1])}</h1><div class="school-meta">发布时间：${esc(x[0])}　来源：校办公室　浏览：${193+i*27}</div><div class="school-rule"></div><p>${bodies[i]||'本通知由校办公室发布，请各班按要求执行。'}</p><p style="text-align:right;margin-top:40px">鹤宁市第二小学<br>${esc(x[0])}</p><div class="school-print">【打印本页】　【关闭窗口】</div></section></div></div></div>`}
function schoolArchive(){return `<div class="site school"><div class="header"><div class="head-inner"><div class="school-name">鹤宁第二小学</div></div></div><div class="nav"><div class="wrap"><span>学校首页</span><span>校史资料</span><span>旧附件镜像</span></div></div><div class="wrap"><div class="crumb">首页 &gt; 校史资料 &gt; 旧附件镜像</div><h2 style="font-size:18px;color:#174d75">1996 年校务附件</h2><p>以下文件为 2009 年校史资料整理时建立的扫描索引。个别学籍字段由纸卡人工录入，缺项保留为空。</p><div class="main-grid"><div><h3 style="font-size:15px">附件目录</h3><div class="table-scroll"><table class="school-table"><tr><th>文件</th><th>日期</th><th>类型</th></tr><tr><td><button class="linklike attach" id="absenceOpen">1996-11-25_三年级考勤汇总.xls</button></td><td>1996-11-25</td><td>XLS</td></tr><tr><td><span class="attach">1996-11_低年级放学管理通知.doc</span></td><td>1996-11-26</td><td>DOC</td></tr><tr><td><span class="attach">1996-12_转学办理汇总.xls</span></td><td>1996-12-06</td><td>XLS</td></tr><tr><td><span class="attach">1996秋_值周记录_三年级.doc</span></td><td>1996-12-18</td><td>DOC</td></tr><tr><td><span class="attach">1996_校医室登记薄_目录.pdf</span></td><td>1997-01-04</td><td>PDF</td></tr></table></div><h3 style="margin-top:24px;font-size:15px">旧学籍查询</h3><div class="search-row"><label>学生姓名<input id="studentName" placeholder="请输入学生姓名"></label><label>出生日期<input id="studentDob" inputmode="numeric" placeholder="请输入何惠出生日期（YYYYMMDD）"></label><button class="action" id="studentSearch">查询</button></div><div id="studentMsg" class="caption"></div></div><aside class="side"><b>资料说明</b><p>旧系统只支持姓名与出生日期联合校验，不提供模糊查询。</p><p class="muted">数据整理：校史办公室<br>最后导入：2012-06-18</p></aside></div><div id="absenceArea" style="margin-top:22px"></div></div></div>`}
function absenceTable(){mark('school6');return `<div class="scan registry-scan"><b>三年级 11 月 25 日考勤异常汇总</b><table class="school-table" style="margin-top:14px"><tr><th>姓名</th><th>班级</th><th>连续缺勤</th><th>备注</th></tr><tr><td>何惠</td><td>三(2)</td><td>2 天</td><td>家属寻找</td></tr><tr><td>冯小兰</td><td>三(1)</td><td>3 天+</td><td>未归</td></tr><tr><td>周斌</td><td>三(4)</td><td>1 天</td><td>家属已接回</td></tr><tr><td>陈晓梅</td><td>三(3)</td><td>1 天</td><td>家属已接回</td></tr><tr><td>王涛</td><td>三(1)</td><td>2 天</td><td>家属寻找</td></tr><tr><td>李文杰</td><td>三(2)</td><td>3 天</td><td><b>市二院肺炎住院</b></td></tr></table><p class="muted" style="margin-top:10px">备注栏按班主任当日登记原样录入，病假、家属寻找和未归均列在同一张异常考勤表中。</p></div>`}
function schoolStudent(){mark('hehui');return `<div class="site school"><div class="header"><div class="head-inner"><div class="school-name">鹤宁市第二小学</div><div class="school-slogan"><b>旧版校史资料</b></div></div></div><div class="school-topnav"><span>学校首页</span><span>校史资料</span><span>旧附件镜像</span><span>学籍查询</span></div><div class="wrap"><div class="school-grid"><aside class="leftmenu"><div><button class="linklike" data-nav="school">学校首页</button></div><div><button class="linklike" data-nav="schoolarchive">旧版资料</button></div><div class="active-old">学籍查询</div><div>档案说明</div></aside><section class="school-content"><div class="crumb">首页 &gt; 校史资料 &gt; 学籍查询结果</div><h2>学生历史记录：何惠</h2><table class="school-table"><tr><th>姓名</th><td>何惠</td><th>出生</th><td>1988-03-09</td></tr><tr><th>原班级</th><td>三年级二班</td><th>状态</th><td>1996-11-29 转出</td></tr><tr><th>异常缺勤</th><td>11/23傍晚起，约41小时</td><th>家属备注</th><td>11/25上午已找到</td></tr></table><div class="school-download-box"><b>关联附件</b><button class="linklike" data-nav="teacher">班主任工作记录_1996-11-27.pdf</button><span>转学申请摘要：家属称学生受惊，近期不宜继续参加集体活动，并要求尽快办理转学。申请表另附手写备注：“走失经过不再向学生本人询问。”</span></div></section></div></div></div>`}
function teacherRecord(){mark('address17');return `<div class="site school"><div class="header"><div class="head-inner"><div class="school-name">鹤宁市第二小学</div><div class="school-slogan"><b>校史资料扫描件</b></div></div></div><div class="school-topnav"><span>学校首页</span><span>校史资料</span><span>旧附件镜像</span><span>扫描阅览</span></div><div class="wrap"><div class="school-grid"><aside class="leftmenu"><div><button class="linklike" data-nav="schoolarchive">返回目录</button></div><div>1996年附件</div><div class="active-old">班主任工作册</div><div>下载说明</div></aside><section class="school-content scan-reader"><div class="scan-toolbar">第 18 / 64 页　　100%　　[上一页] [下一页] [打印]</div><div class="scan stamp"><p>11月27日，何惠返校。早上点名时我按平时习惯叫了“惠惠”，她没有答应，连头也没抬；改叫“何惠”以后，她才说到。</p><p>第一节课前她在第三排靠窗的位置坐下，那不是她的座位。同桌叫了她两次，她看了半天，才回到原来的位置。</p><p>中午我问她家里住哪，她说“槐树巷17号”。我以为她还没缓过来，又问了一遍，她还是这么说。何惠母亲下午来学校，听见这个地址后脸色很不好，只说孩子这两天吓坏了，让我们不要再问。</p><p>家长另外提出，这阵子在学校只叫大名，不要再叫“惠惠”。11月29日办理转学。</p></div><p class="muted">记录人：三年级二班班主任　原件为手写工作册扫描件。</p><div class="school-download-box archive-crossref"><b>校史整理附注（2009）</b><span>整理人员曾用南关居民旧论坛的校友回忆核对当年称呼与街巷名称，相关公开帖仍可访问。</span><button class="linklike" data-nav="forum">南关人家旧论坛</button></div></section></div></div></div>`}

function forumHome(){const homeIds=[1,2,4,6,7,8,9,10,11,12,13];return `<div class="site forum"><div class="topline">南关人家　&gt;　论坛首页　　欢迎，游客　 <span>注册 | 登录 | 社区服务 | 帮助</span></div><div class="wrap"><div class="logo"><b>南关人家</b><span>一起说说我们身边的事</span></div><div class="forum-nav"><span>论坛首页</span><span>生活休闲</span><span>本地新闻</span><span>房屋租售</span><span>求职招聘</span><span>亲子教育</span></div><div class="bbs-tools"><input id="forumKw" placeholder="帖子 / 用户 / 街道"><button id="forumSearch" class="action">搜索老帖</button>　今日 42　昨日 108　主题 18,642</div><div class="thread-list">${homeIds.map(i=>{const t=forumThreads[i];return `<div class="thread-row"><div><button class="linklike" data-thread="${i}">${t[1]}</button><div class="muted">${t[0]}</div></div><div>${t[2]}</div><div>${t[3]} 回复</div></div>`}).join('')}</div><div class="pager">首页　1　2　3　4　…　下一页　　版主：南关照相馆 / 老何修车</div></div></div>`}
function forumSearch(q=''){const kw=decodeURIComponent(q||'').trim();let inds=kw?forumThreads.map((t,i)=>[t,i]).filter(([t])=>t.slice(0,3).join(' ').includes(kw)||( /兰兰|猫脸|老太太|老人/.test(kw)&&/猫脸/.test(t[1]))||( /槐树巷|门牌/.test(kw)&&/槐树巷/.test(t[1]))||( /早市|孩子|2012|走失/.test(kw)&&/找孩子/.test(t[1]))).map(x=>x[1]):[];return `<div class="site forum"><div class="topline">南关人家 BBS · 搜索</div><div class="wrap"><p><button class="linklike" data-nav="forum">← 返回论坛</button></p><h3>搜索：${esc(kw)}</h3><div class="thread-list">${inds.length?inds.map(i=>{const t=forumThreads[i];return `<div class="thread-row"><div><button class="linklike" data-thread="${i}">${t[1]}</button><div class="muted">${t[0]}</div></div><div>${t[2]}</div><div>${t[3]} 回复</div></div>`}).join(''):'<div class="bbs-empty">没有找到符合条件的帖子。</div>'}</div></div></div>`}
function forumThread(i){i=Number(i);if(i===3)mark('zhao');if(i===0)mark('neighbor');const t=forumThreads[i]||forumThreads[1];let posts='';if(i===3)posts=`${post('锅炉房老李','2005-11-21 21:08','九几年那阵确实闹得吓人，不过我在南关锅炉房上夜班，真没见过她追孩子。她见着人就问一句“兰兰回去了没有”，一晚上问了好几拨人。')} ${post('旧邮局','2005-11-21 21:44','我记得也是“回去了没有”，不是“见没见兰兰”。我那时候就觉得这话怪，孩子明明刚丢，她问得倒像兰兰本来知道该回哪儿。')} ${post('槐树下喝茶','2005-11-22 08:16','兰兰是她外孙女冯小兰。孩子那晚没回来，老太太第二天清早就没了。后来守灵院里又跑进去一只黑猫，这几件事搅在一起，后面越传越不像原来的样子。')} ${post('锅炉房老李','2005-11-22 09:03','学校没停课，停的是晚自习。家长都堵在校门口接孩子，后来网上才传成全城停课。')} ${post('南关照相馆','2005-11-22 10:26','文化馆前几年做过一批南关老人访谈，里面好像有人提过小名和守灵的讲究。资料站还在：<button class="linklike" data-nav="culture">culture.hening.local</button>。')}`;
else if(i===0)posts=`${post('槐树下喝茶','2012-10-04 07:21','昨天下午我去西郊旧二路车终点买零件，看见一个女的抱着小姑娘哭。听旁边人说孩子前天下午在南关早市走散，昨天三点多才找到，算下来三十多个小时。')} ${post('南关照相馆','2012-10-04 09:18','是不是东河路何家的？前晚确实有人在早市附近问孩子，可我没见他们贴过寻人启事。')} ${post('槐树下喝茶','2012-10-04 10:40','应该就是她家。小姑娘看着没受伤，就是一直不肯上她妈那辆车。她妈跟她说“回家了”，她问了一句“还是回你家吗？”我当时还以为孩子吓糊涂了。')}`;
else {const ordinary={1:['二路车现在改到东河桥那边折返了，老终点牌子还在，司机一般不叫那个名字了。','老何修车','我昨天坐的末班，过南关早市大概六点四十。'],2:['房子已经租出去了，多谢大家。','小北风','南关这边一室一厅最近涨得挺快，东河路稍便宜。'],4:['后门在操场北边，九十年代末砌墙封了。','南关照相馆','小时候放学总从那边抄近路，后来值班室搬过去就不让走了。'],5:['槐树巷拆之前门牌很乱，单双号还不完全挨着。','旧邮局','17号靠里，不在大路边，送信得从井台旁边拐进去。'],6:['老赵家那家糖糕早没了，现在早市口那摊不是一家的。','三轮车王师傅','以前两毛一个，冬天刚出锅最好吃。'],7:['89级三班我认识两个，姓孙和姓胡的，私信你电话。','梅子','毕业照我家里可能还有，周末找找。'],8:['东河口那边的老周还修，就是零件不一定有。','东河口','要是熊猫牌收音机先说型号。'],9:['搬到桥底以后摊位少了一半，买菜确实没以前方便。','小叶子','周六人还是多，早点去。'],10:['我手里有一张2001年的，2路终点已经改过一次。','二厂宿舍','要老版得去公交公司档案室问。'],11:['实验小学门口有个退休语文老师，姓陈。','秋雨','不接太小的孩子，三年级往上。'],12:['澡堂是03年春节后彻底关的，后来改成仓库。','老邢','门脸还在，招牌被拆了。'],13:['凤凰28能修，先看看飞轮和链条是不是一起坏。','一把扳手','我周末在二厂宿舍门口。']}[i]||['这两天没听说有变化。',t[2],'有消息再补。'];posts=`${post(t[2],t[0]+' 18:20',ordinary[0])} ${post(ordinary[1],t[0]+' 19:03',ordinary[2])}`;}
return `<div class="site forum"><div class="topline">南关人家　&gt;　本地话题　　欢迎，游客　 <span>注册 | 登录 | 社区服务 | 帮助</span></div><div class="wrap"><div class="logo compact-logo"><b>南关人家</b><span>一起说说我们身边的事</span></div><div class="forum-nav"><span>论坛首页</span><span>生活休闲</span><span>本地新闻</span><span>房屋租售</span><span>亲子教育</span></div><div class="bbs-breadcrumb"><button class="linklike" data-nav="forum">南关人家</button> &gt; 本地话题 &gt; 帖子正文</div><div class="thread-title-old"><h2>${esc(t[1])}</h2><span>查看：${t[3]*37}　回复：${t[3]}</span></div>${posts}<div class="pager">返回列表　|　上一主题　|　下一主题</div></div></div>`}
function post(user,time,body){return `<div class="post"><div class="post-user"><b>${esc(user)}</b><br><span class="muted">注册居民</span></div><div class="post-body"><span class="floor">${esc(time)}</span>${body}<div class="sig">来自：鹤宁 · 南关</div></div></div>`}

function cultureHome(){const homeIds=[2,3,6,7,8,9,10,1];return `<div class="site culture"><div class="head"><div class="culture-seal">文</div><div><div class="title">鹤宁地方文化馆</div><div class="culture-en">HENING LOCAL CULTURE MUSEUM</div></div><div class="culture-tagline">传承地方文化　记录城市记忆</div></div><div class="bar"><span>首页</span><span>本馆介绍</span><span>馆藏资源</span><span>非遗民俗</span><span>地方志</span><span>展览活动</span><span>资料下载</span></div><div class="wrap"><div class="culture-layout"><aside class="culture-left"><div>首页</div><div>本馆概况</div><div class="active">民间习俗</div><div>非遗文化</div><div>民俗风情</div><div>地方志</div><div>馆藏资料</div><div>活动展览</div></aside><main><div class="crumb">当前位置： 首页 &gt; 民俗资料 &gt; 资料目录</div><div class="culture-notice"><b>资料站公告：</b> 部分口述资料保留方言原句，引用请注明采集年份。</div><h2>地方资料目录</h2>${homeIds.map(i=>{const x=cultureEntries[i];return `<div class="entry"><button class="linklike" data-culture="${i}">${x[1]}</button><div class="muted">[${x[0]}]　${x[2]}</div></div>`}).join('')}</main><aside class="culture-side"><img src="assets/festival.jpg" alt="地方活动旧照"><div class="site-photo-caption">图：南关庙会旧照（2006，馆藏资料）</div><h3>站内资料检索</h3><input id="cultureKw" placeholder="题名 / 关键词"><button id="cultureSearch" class="action">检索</button><p>开放时间<br>周二至周日 09:00—16:30</p></aside></div></div></div>`}
function cultureSearch(q=''){const kw=decodeURIComponent(q||'').trim();let inds=kw?cultureEntries.map((x,i)=>[x,i]).filter(([x])=>x.join(' ').includes(kw)||( /乳名|小名|守灵|猫/.test(kw)&&/守灵|乳名/.test(x[1]))||( /槐树巷|门牌/.test(kw)&&/街巷|门牌/.test(x[1]))).map(x=>x[1]):[];return `<div class="site culture"><div class="head"><div class="title">鹤宁地方文化馆</div></div><div class="wrap"><p><button class="linklike" data-nav="culture">← 返回目录</button></p><h2>检索：${esc(kw)}</h2>${inds.length?inds.map(i=>{const x=cultureEntries[i];return `<div class="entry"><button class="linklike" data-culture="${i}">${x[1]}</button><div class="muted">${x[0]}　${x[2]}</div></div>`}).join(''):'<p>没有检索到相关资料。</p>'}</div></div>`}
function cultureArticle(i){i=Number(i);const x=cultureEntries[i]||cultureEntries[2];if(i===0||i===5)mark('folkname');if(i===4)mark('address17');let body='';if(i===0)body=`<p>鹤宁旧式丧俗里，守灵期间忌猫狗近棺，这一点在多份南关口述资料里都能见到。与后来“猫越尸会诈尸”的说法不同，老人更常提到的是孩子的称呼。</p><p>2006年的一份采访里，受访者说：“小名是家里人才叫的。孩子刚受过惊，晚上有人在院外头喊小名，先别让他答应；真答应了，也先开灯看看再开门。”</p><p>同一批口述里还有一句较短的说法：“猫若蹿灵，孩子先莫叫乳名。”不同受访者给出的理由并不一致，有人说是怕孩子受惊，也有人只说“老辈一直这么教”。</p><p>馆方未在正式地方志中找到统一仪式或明确出处。</p>`;else if(i===5)body=`<p>老城区家庭对孩子的乳名使用很随意，但在走失、惊吓、丧事之后临时改叫大名的做法并不少见。受访者通常把它解释成“压惊”，并不认为这是正式仪式。</p><p>一位南关老人回忆，家里孩子走失后找回来，长辈会先叫大名，等孩子“自己认人、认门、认床了”，才重新叫小名。她说：“不是怕名字，是怕叫早了。”</p>`;else if(i===4)body=`<div class="scan-thumb">纸本扫描缩略图<br>《南关旧门牌册》<br>第 17 页</div><p>槐树巷在 2000 年旧城改造后并入南关路。1987—1998 年门牌表如下：</p><p class="culture-ref">原始门牌对照表由市图书馆地方文献中心保存。<button class="linklike" data-nav="library">查看馆藏目录</button></p><table class="school-table"><tr><th>旧门牌</th><th>户主 / 使用人</th><th>新编号</th></tr><tr><td>槐树巷 15 号</td><td>钱守义</td><td>南关路 88 号</td></tr><tr><td><b>槐树巷 17 号</b></td><td><b>赵淑琴 / 冯家</b></td><td>拆除</td></tr><tr><td>槐树巷 19 号</td><td>街道仓房</td><td>拆除</td></tr></table>`;else {const misc={1:'<p>老城区街巷在口语中常用旧称。东河路北段曾被居民叫作“机修街”，井台胡同在不同年份的地图上也有两种写法。</p><p>本条录音整理于2008年春，受访者均为南关长期居民。</p>',2:'<p>2006年城隍庙会恢复后，馆员对居民捐赠照片重新编号。照片多为普通家庭相机拍摄，画面中可见临时戏台、糖画摊和旧公交站牌。</p><p>原照色偏严重，数字化时未作修色。</p>',3:'<p>冬至前后，南关旧住户多做酸菜、炖豆腐和面食。八十年代煤票紧张时，几户人家常合用一口大锅。</p>',6:'<p>旧街改造前，早市、澡堂、二路车终点和二小后门构成了附近居民最常走的生活路线。几位受访者对年份记得不完全一样，馆方按能核实的资料另加了注释。</p>',7:'<p>馆藏剪纸以窗花、喜字、花鸟和生肖为主。2007年冬完成第一轮数字化，部分底纸已有折痕和虫蛀。</p>',8:'<p>2009年度共接受居民捐赠资料136件，其中旧照片61张、票证28件、手写日记和账册17册。</p>',9:'<p>老城区对孩子的称呼常随家庭而异，“小名”“乳名”“家名”在口述中混用，并没有严格分类。</p>',10:'<p>东河路原为城南土路，九十年代拓宽后并入公交线路。沿线的机修铺、粮店和旧澡堂大多在2000年前后搬迁。</p>'};body=misc[i]||'<p>本页为馆藏普通资料条目，整理自居民捐赠与历年走访记录。</p>';}return `<div class="site culture"><div class="head"><div class="culture-seal">文</div><div><div class="title">鹤宁地方文化馆</div><div class="culture-en">HENING LOCAL CULTURE MUSEUM</div></div><div class="culture-tagline">传承地方文化　记录城市记忆</div></div><div class="bar"><span>首页</span><span>本馆介绍</span><span>馆藏资源</span><span>非遗民俗</span><span>地方志</span><span>展览活动</span><span>资料下载</span></div><div class="wrap"><div class="culture-layout"><aside class="culture-left"><div><button class="linklike" data-nav="culture">资料目录</button></div><div class="active">民间习俗</div><div>非遗文化</div><div>地方志</div><div>馆藏资料</div></aside><main class="article culture-article"><div class="crumb">当前位置：首页 &gt; ${esc(x[0])} &gt; 正文</div><h1>${esc(x[1])}</h1><div class="muted">资料类别：${esc(x[0])}　整理日期：${esc(x[2])}</div>${body}<div class="culture-footnote">资料整理：地方文化资料室　引用请注明资料标题与整理日期。</div></main><aside class="culture-side article-side"><h3>相关栏目</h3><p>民间习俗</p><p>口述资料</p><p>旧街巷</p><p>地方志</p></aside></div></div></div>`}

function libraryHome(){return `<div class="site library"><div class="head"><div class="libname">鹤宁市图书馆 · 地方文献中心</div></div><div class="nav">馆藏目录　数字报刊　地方志　旧地图　社区资料　读者服务</div><div class="wrap"><h2>地方文献联合检索</h2><div class="search-row"><label>题名 / 关键词<input id="libKw" placeholder="题名 / 关键词"></label><label>资料类型<select><option>全部类型</option><option>报刊</option><option>地方志</option><option>社区资料</option></select></label><button class="action" id="libSearch">检索</button></div><div style="margin-top:24px"><div class="muted" style="font-size:11px;padding-bottom:7px;border-bottom:2px solid #496b77">地方文献专题库 · 共 8,412 条书目记录</div>${libEntries.map((x,i)=>`<div class="lib-result"><div class="lib-code">${x[0]}</div><button class="linklike" data-lib="${i}">${x[1]}</button><div class="muted">${x[2]} · 馆内阅览 / 数字镜像</div></div>`).join('')}</div></div></div>`}
function librarySearch(q=''){const kw=decodeURIComponent(q||'').trim();let inds=libEntries.map((x,i)=>[x,i]).filter(([x])=>!kw||x.join(' ').includes(kw)||( /门牌|槐树巷/.test(kw)&&/门牌|地图/.test(x[1]))||( /南关|2012|沈妍/.test(kw)&&/南关|社区|交通|照片/.test(x[1]))).map(x=>x[1]);return `<div class="site library"><div class="head"><div class="libname">鹤宁市图书馆 · 检索结果</div></div><div class="wrap"><p><button class="linklike" data-nav="library">← 返回</button></p><h2>关键词：${esc(kw)}</h2>${inds.length?inds.map(i=>{const x=libEntries[i];return `<div class="lib-result"><div class="lib-code">${x[0]}</div><button class="linklike" data-lib="${i}">${x[1]}</button><div class="muted">${x[2]}</div></div>`}).join(''):'<p>未找到匹配书目。</p>'}</div></div>`}
function libraryDoc(i){i=Number(i);let body='';if(i===1){mark('address17');body=`<h2>南关街道旧门牌对照表</h2><table class="school-table"><tr><th>旧址</th><th>登记户主</th><th>备注</th></tr><tr><td>槐树巷 17 号</td><td><b>赵淑琴</b></td><td>冯家长期居住</td></tr><tr><td>东河路 42 号</td><td>何家</td><td>1996 年底迁出</td></tr></table>`}else if(i===2){body=`<h2>鹤宁第二小学 1996 年校务附件镜像</h2><p>本目录由学校2009年校史整理项目移交，包含考勤汇总、转学登记、值周记录和校医室目录等扫描件。</p><p>原件中涉及学生姓名的页面只在馆内终端开放，在线镜像保留目录与页码索引。</p><p class="muted">索引范围：1996-09 至 1997-01　共 43 页。</p>`}else if(i===3){body=`<h2>南关居民口述资料第九辑</h2><p>本辑收录 2008—2010 年社区交通、早市、拆迁回忆，部分内容来自居民自行保存的论坛打印页和采访录音。</p><p class="muted">索引词：南关早市；旧二路终点；二小后门；社区论坛。</p>`}else if(i===5){body=`<h2>鹤宁地方习俗资料汇编</h2><p>本册整理丧葬、婚嫁、儿童称谓和节令饮食等口述资料。编者在序言中注明，同一种说法在不同街区常有完全不同的解释，不能当作统一礼俗。</p><p>“乳名与避讳”一节收录过一句南关口述：“孩子刚从外头找回来，先别急着叫小名，等他自己把家里的人和东西认全了再说。”</p><p class="muted">馆藏号：HN-ALM-2008-01　纸本第 84—87 页。</p>`}else {const d=libEntries[i];body=`<h2>${esc(d?.[1]||'地方文献')}</h2><p>馆藏号：${esc(d?.[0]||'—')}　资料类型：${esc(d?.[2]||'地方资料')}</p><p>数字镜像仅供阅览。原件保存于地方文献库，纸本有装订磨损、页边批注或年代性污渍，引用时请以馆藏号登记。</p><p class="muted">最近一次数字化校对：2019-06</p>`;}return `<div class="site library"><div class="head"><div class="libname">鹤宁市图书馆 · 地方文献中心</div></div><div class="nav">馆藏目录　数字报刊　地方志　旧地图　社区资料　读者服务</div><div class="wrap"><div class="lib-breadcrumb"><button class="linklike" data-nav="library">地方文献首页</button> &gt; 馆藏阅览</div><div class="library-reader"><aside><b>文献工具</b><p>馆藏信息</p><p>引用格式</p><p>打印本页</p><p>加入临时书架</p></aside><div class="doc-view">${body}</div></div></div></div>`}

function bindRoute(r){
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));
 document.querySelectorAll('[data-news]').forEach(b=>b.onclick=()=>nav('newsarticle:'+b.dataset.news));
 document.querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>nav('thread:'+b.dataset.thread));
 document.querySelectorAll('[data-culture]').forEach(b=>b.onclick=()=>nav('culturearticle:'+b.dataset.culture));
 document.querySelectorAll('[data-lib]').forEach(b=>b.onclick=()=>nav('libdoc:'+b.dataset.lib));
 document.querySelectorAll('[data-schoolnotice]').forEach(b=>b.onclick=()=>nav('schoolnotice:'+b.dataset.schoolnotice));
 const doNewsSearch=()=>{const kw=document.getElementById('newsKw').value.trim();const f=document.getElementById('newsFrom')?.value.trim()||'';const t=document.getElementById('newsTo')?.value.trim()||'';nav('newssearch:'+encodeURIComponent([kw,f,t].join('|')))}; document.getElementById('newsSearch')?.addEventListener('click',doNewsSearch); document.getElementById('newsSearch2')?.addEventListener('click',doNewsSearch); ['newsKw','newsFrom','newsTo'].forEach(id=>document.getElementById(id)?.addEventListener('keydown',e=>{if(e.key==='Enter')doNewsSearch()}));
 const doForum=()=>nav('forumsearch:'+encodeURIComponent(document.getElementById('forumKw').value.trim())); document.getElementById('forumSearch')?.addEventListener('click',doForum); document.getElementById('forumKw')?.addEventListener('keydown',e=>{if(e.key==='Enter')doForum()});
 const doCulture=()=>nav('culturesearch:'+encodeURIComponent(document.getElementById('cultureKw').value.trim())); document.getElementById('cultureSearch')?.addEventListener('click',doCulture); document.getElementById('cultureKw')?.addEventListener('keydown',e=>{if(e.key==='Enter')doCulture()});
 const doLib=()=>nav('librarysearch:'+encodeURIComponent(document.getElementById('libKw').value.trim())); document.getElementById('libSearch')?.addEventListener('click',doLib); document.getElementById('libKw')?.addEventListener('keydown',e=>{if(e.key==='Enter')doLib()});
 document.getElementById('absenceOpen')?.addEventListener('click',()=>{document.getElementById('absenceArea').innerHTML=absenceTable();renderAnchor()});
 const doStudent=()=>{const n=document.getElementById('studentName').value.trim();const d=document.getElementById('studentDob').value.trim().replace(/[-/.]/g,'');if(n==='何惠'&&d==='19880309')nav('schoolstudent');else document.getElementById('studentMsg').textContent='未找到匹配记录。请核对姓名与出生日期。'}; document.getElementById('studentSearch')?.addEventListener('click',doStudent); ['studentName','studentDob'].forEach(id=>document.getElementById(id)?.addEventListener('keydown',e=>{if(e.key==='Enter')doStudent()}));
}

function triggerBlackout(){
 if(!C.shouldBlackout(state)){win='unsorted';render();return}
 state=C.markBlackout(state);save();blackout.classList.add('show');blackout.classList.remove('text-on');blackout.setAttribute('aria-hidden','false');lowTone();
 setTimeout(()=>blackout.classList.add('text-on'),700);
 setTimeout(()=>{blackout.classList.remove('show','text-on');blackout.setAttribute('aria-hidden','true');win='unsorted';render()},3000);
}
function renderEnd(){
 app.innerHTML=`<div class="end-screen" style="background:#0d2231 url('assets/wallpaper.jpg') center/cover no-repeat"><div class="end-inner"><div style="font-size:12px;color:#9aa8b0;margin-bottom:22px">Windows 已锁定</div><div class="photo-frame" style="padding:5px;border-color:#8aa0ad;background:#dfe7ea"><img src="assets/mother_child_photo.jpg" alt="母女合影" style="width:152px;max-width:42vw"></div><div style="font-size:21px;margin-top:12px;text-shadow:0 1px 2px #000">沈妍</div><div class="end-note">照片信息：回家第二天。</div><div class="end-small">母亲留下的旧箱子已由家属送到医院。没有新的消息。</div><div style="margin-top:54px;color:#a9b2b7;font-size:11px">结束</div><button id="restartEnd" style="margin-top:17px;background:rgba(20,30,36,.56);border:1px solid #6d7d85;color:#c4cbd0;padding:6px 11px">重新开始</button></div></div>`;
 document.getElementById('restartEnd').onclick=()=>confirm('确定重新开始？')&&reset();
}
// Initial bind / delegated local window bindings after each desktop render.
const originalRender=render;
render=function(){originalRender();if(win&&win!=='browser')bindLocal()};
['pointerdown','keydown','wheel','touchstart'].forEach(ev=>document.addEventListener(ev,noteActivity,{passive:true}));
armIdleHint();
render();
})();
