(()=>{
'use strict';
const C=window.RenShengCore;
const KEY='rensheng_v2_state';
let memoryState=null;
function load(){
  for(const store of [localStorage,sessionStorage]){try{const v=store.getItem(KEY);if(v)return JSON.parse(v)}catch(e){}}
  return memoryState;
}
function persist(v){memoryState=v;for(const store of [localStorage,sessionStorage]){try{store.setItem(KEY,JSON.stringify(v));return}catch(e){}}}
let state=C.normalize(load());
let win='syfolder',minimizedWin=null,winMax=false;
let browserRoute='home',browserTabs=[],historyStack=[],historyIndex=-1;
let anchorOpen=false,hintLevel=0,idleTimer=null;
const app=document.getElementById('app');
function save(){persist(state)}
function reset(){try{localStorage.removeItem(KEY)}catch(e){}try{sessionStorage.removeItem(KEY)}catch(e){}memoryState=null;state=C.fresh();win='syfolder';minimizedWin=null;winMax=false;browserRoute='home';browserTabs=[];historyStack=[];historyIndex=-1;hintLevel=0;render()}
function mark(k){state=C.mark(state,k);hintLevel=0;save();renderAnchor()}
function has(k){return C.has(state,k)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function clock(){const d=new Date();return d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}
function armIdleHint(){clearTimeout(idleTimer);idleTimer=setTimeout(()=>{if(state.ended)return;document.getElementById('anchorToggle')?.classList.add('idle-hint')},90000)}
function noteActivity(){armIdleHint()}
function desktopHTML(){
  const activeTask=win?taskLabel(win):(minimizedWin?taskLabel(minimizedWin):'');
  return `<div class="os"><div class="desktop"><div class="desk-icons">
    ${deskIcon('computer','computer','我的电脑')}
    ${deskIcon('folder','syfolder','沈妍的资料')}
    ${deskIcon('folder','unsorted','未整理')}
    ${deskIcon('browser','browser','Internet Explorer')}
    ${deskIcon('sheet','timeline','调查记录.xls')}
    ${deskIcon('tmp','doc','维修说明.txt')}
  </div><div id="startMenu" class="start-menu" aria-hidden="true"><div class="start-user"><div class="start-avatar">沈</div><b>沈妍</b></div><div class="start-columns"><div class="start-left">
    <button data-open="browser"><img src="assets/icons/browser.png" alt="">Internet Explorer</button>
    <button data-open="syfolder"><img src="assets/icons/folder.png" alt="">我的文档</button>
    <hr><button data-open="timeline"><img src="assets/icons/sheet.png" alt="">调查记录.xls</button>
  </div><div class="start-right"><button data-open="computer">我的电脑</button><hr><button data-open="search">搜索</button></div></div><div class="start-footer"><span>注销</span><span>关闭计算机</span></div></div></div>
  <div class="taskbar"><button class="start-button" id="startButton"><span class="start-flag"></span><b>开始</b></button><div class="quick-launch"><button data-open="browser" title="Internet Explorer"><img src="assets/icons/browser.png" alt=""></button><button data-open="syfolder" title="我的文档"><img src="assets/icons/folder.png" alt=""></button></div>${activeTask?`<button class="task-app ${minimizedWin&&!win?'minimized-task':''}" ${minimizedWin&&!win?`data-restore="${minimizedWin}"`:`data-open="${win||minimizedWin}"`}><span>${esc(activeTask)}</span></button>`:''}<div class="tray"><span class="tray-net"></span><span class="tray-speaker"></span><button id="anchorToggle" class="tray-help" title="需要一点提示时点这里">?</button><div class="clock">${clock()}<br>2026/09/13</div></div></div>
  <div id="anchorPanel" class="anchor-panel xp-balloon"></div></div>`;
}
function deskIcon(cls,id,label){return `<button class="desk-icon" data-open="${id}" title="双击打开 ${esc(label)}"><img class="desk-ico-img" src="assets/icons/${cls}.png" alt=""><span>${esc(label)}</span></button>`}
function taskLabel(id){if(id.startsWith('local:'))return id.slice(6);return({computer:'我的电脑',syfolder:'沈妍的资料',unsorted:'未整理',browser:'Internet Explorer',timeline:'调查记录.xls',doc:'维修说明.txt',search:'搜索',private:'BACKUP_OLD',photo:'IMG_2002.jpg',folder:'1996资料'}[id]||id)}
function render(){if(state.ended){renderEnd();return}app.innerHTML=desktopHTML()+(win?(win==='browser'?'':windowHTML(win)):'');bindDesktop();if(win==='browser')renderBrowserShell();else if(win)bindLocal();renderAnchor();setTimeout(()=>document.getElementById('boot')?.classList.add('hide'),350)}
function bindDesktop(){
  const coarse=matchMedia('(pointer:coarse)').matches;
  document.querySelectorAll('[data-open]:not(.desk-icon)').forEach(b=>b.onclick=e=>{e.stopPropagation();openWin(b.dataset.open)});
  document.querySelectorAll('.desk-icon').forEach(b=>{b.onclick=e=>{e.stopPropagation();document.querySelectorAll('.desk-icon.selected').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');if(coarse)openWin(b.dataset.open)};b.ondblclick=e=>{e.preventDefault();e.stopPropagation();openWin(b.dataset.open)};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openWin(b.dataset.open)}}});
  document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{win=b.dataset.restore;minimizedWin=null;render()});
  const sb=document.getElementById('startButton'),sm=document.getElementById('startMenu');if(sb&&sm)sb.onclick=e=>{e.stopPropagation();sm.classList.toggle('show');sm.setAttribute('aria-hidden',sm.classList.contains('show')?'false':'true')};
  document.querySelector('.desktop')?.addEventListener('click',e=>{if(!e.target.closest('.start-menu')&&!e.target.closest('#startButton'))document.getElementById('startMenu')?.classList.remove('show')});
}
function renderAnchor(){
  const p=document.getElementById('anchorPanel');if(!p)return;const h=C.hintSet(state),pct=C.completion(state);const idx=Math.min(hintLevel+1,2);
  p.innerHTML=`<button class="balloon-close" id="anchorClose">×</button><b>${esc(h[0])}</b><div class="sub">${esc(h[idx])}</div><div style="margin-top:8px;font-size:11px;color:#566">调查进度 ${pct}%${hintLevel<1?`　<button id="hintMore" class="linklike">再给一点</button>`:''}</div>`;
  p.classList.toggle('show',anchorOpen);document.getElementById('anchorClose')?.addEventListener('click',()=>{anchorOpen=false;renderAnchor()});document.getElementById('hintMore')?.addEventListener('click',()=>{hintLevel=1;renderAnchor()});
  const t=document.getElementById('anchorToggle');if(t){t.onclick=()=>{anchorOpen=!anchorOpen;renderAnchor()};if(anchorOpen)t.classList.remove('idle-hint')}
}
function openWin(id){if(id==='browser'){openBrowser(browserRoute);return}minimizedWin=null;winMax=false;win=id;render()}
function closeWin(){if(win==='timeline'&&has('final_date')&&has('final_photo')){state.ended=true;save();win=null;render();return}win=null;minimizedWin=null;winMax=false;render()}
function windowHTML(id){
  let title='',body='',small=false,type='explorer',toolbar='',menubar='',status='就绪';
  const xpMenu='<div class="classic-menu">文件(F)　编辑(E)　查看(V)　收藏(A)　工具(T)　帮助(H)</div>';
  const explorerToolbar=path=>`<div class="win-toolbar xp-toolbar"><button class="xp-tool nav-arrow">←</button><button class="xp-tool nav-arrow muted-tool">→</button><button class="xp-tool nav-arrow">↑</button><span class="xp-sep"></span><button class="xp-tool wide" data-open="search"><span class="mini-search"></span>搜索</button><button class="xp-tool wide"><img src="assets/icons/folder.png" alt="">文件夹</button><span class="xp-sep"></span><div class="crumbbox"><b>地址</b>　${path}</div></div>`;
  if(id.startsWith('local:')){const sp=localFileSpec(id.slice(6));({title,type='notepad',menubar='',toolbar='',body='',status='就绪'}=sp)}
  if(id==='doc'){title='维修说明.txt - 记事本';small=true;type='notepad';menubar='<div class="classic-menu">文件(F)　编辑(E)　格式(O)　查看(V)　帮助(H)</div>';body=`<div class="note-paper notepad-paper">送修时机器可以正常识别硬盘。按家属要求，只做系统启动修复和只读镜像，没有整理原文件。<br><br>浏览器处于脱机状态，只能打开以前保存过的页面。<br><br>旧版同步账户：sy0718<br><br>— 鹤宁科维电脑维修　2026.09.12</div><div class="notepad-footer"><button id="resetBtn" class="classic-button">清除本地进度重新开始</button></div>`}
  if(id==='computer'){title='我的电脑';menubar=xpMenu;toolbar=explorerToolbar('我的电脑');body=myComputerHTML();status='3 个对象'}
  if(id==='syfolder'){title='沈妍的资料';menubar=xpMenu;toolbar=explorerToolbar('C:\\Documents and Settings\\沈妍\\我的文档\\沈妍的资料');body=syFolderHTML();status='3 个对象'}
  if(id==='unsorted'){title='未整理';menubar=xpMenu;toolbar=explorerToolbar('C:\\Documents and Settings\\沈妍\\桌面\\未整理');body=unsortedHTML();status='2 个对象'}
  if(id==='folder'){title='1996资料';menubar=xpMenu;toolbar=explorerToolbar('C:\\Documents and Settings\\沈妍\\我的文档\\沈妍的资料\\1996资料');body=folderHTML();status='2 个对象'}
  if(id==='timeline'){title='调查记录.xls - Microsoft Excel';type='sheet-viewer';menubar='<div class="classic-menu">文件(F)　编辑(E)　视图(V)　插入(I)　格式(O)　工具(T)　数据(D)　窗口(W)　帮助(H)</div>';toolbar='<div class="excel-ribbon classic-toolbar"><button>打开</button><button>保存</button><button>打印</button><span class="xp-sep"></span><span>字体：宋体　字号：10　<b>B</b>　<i>I</i>　<u>U</u>　Σ</span></div><div class="formula-bar"><span class="namebox-mini">A1</span><span>fx</span><div>事件时间线</div></div>';body=timelineHTML()}
  if(id==='private'){title='BACKUP_OLD';type='private-window';menubar='<div class="classic-menu">文件(F)　安全(S)　帮助(H)</div>';body=privateLoginHTML();status='本地只读备份'}
  if(id==='search'){title='搜索结果';type='search-window';body=searchHTML();status='准备搜索'}
  if(id==='photo'){title='IMG_2002.jpg - Windows 图片和传真查看器';type='photo-viewer';toolbar='<div class="photo-tools"><button>放大</button><button>缩小</button><button>打印</button></div>';body=photoHTML();status='IMG_2002.jpg'}
  return `<section class="window center ${winMax?'maximized ':''}${small?'small ':''}${type}"><div class="titlebar"><span class="window-app-icon ${type}"></span><strong>${esc(title)}</strong><button class="win-min" id="winMin">_</button><button class="win-max" id="winMax">□</button><button class="win-close" id="winClose">×</button></div>${menubar}${toolbar}<div class="window-body">${body}</div><div class="window-status">${status}</div></section>`;
}
function xpExplorerLayout(sideTitle,sideItems,main){return `<div class="explorer-layout"><aside class="explorer-tree xp-tasks"><div class="xp-taskbox"><h4>${sideTitle}</h4>${sideItems}</div><div class="xp-taskbox pale"><h4>其他位置</h4><button data-open="syfolder">我的文档</button><button data-open="computer">我的电脑</button><button data-open="search">搜索</button></div></aside><section class="explorer-main">${main}</section></div>`}
function myComputerHTML(){return xpExplorerLayout('系统任务','<button data-open="search">搜索文件或文件夹</button>',`<h3 class="explorer-section-title">存储在此计算机上的文件</h3><div class="xp-drive-list"><button class="xp-drive" data-open="syfolder"><img src="assets/icons/folder.png" alt=""><span><b>沈妍的文档</b><small>文件夹</small></span></button></div><h3 class="explorer-section-title">硬盘驱动器</h3><div class="xp-drive-list"><button class="xp-drive" data-open="syfolder"><img src="assets/icons/drive_c.png" alt=""><span><b>本地磁盘 (C:)</b><small>38.2 GB 可用，共 74.5 GB</small><i><em style="width:48%"></em></i></span></button><button class="xp-drive" data-open="private"><img src="assets/icons/drive_d.png" alt=""><span><b>资料盘 (D:)</b><small>BACKUP_OLD · 只读</small><i><em style="width:54%"></em></i></span></button></div>`)}
function syFolderHTML(){return xpExplorerLayout('文件和文件夹任务','<button class="static-task">按名称排列</button>',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-local="start"><img src="assets/icons/tmp.png" alt=""><span>调查起点.txt</span></button><button class="explorer-file" data-open="folder"><img src="assets/icons/folder.png" alt=""><span>1996资料</span></button><button class="explorer-file" data-open="timeline"><img src="assets/icons/sheet.png" alt=""><span>调查记录.xls</span></button></div>`)}
function unsortedHTML(){return xpExplorerLayout('文件和文件夹任务','<button class="static-task">按日期排列</button>',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-local="unsorted1"><img src="assets/icons/tmp.png" alt=""><span>待核_0911.txt</span></button><button class="explorer-file" data-local="map"><img src="assets/icons/imagefile.png" alt=""><span>南关地图_1994.jpg</span></button></div>`)}
function folderHTML(){return xpExplorerLayout('文件和文件夹任务','<button class="static-task">按类型排列</button>',`<div class="explorer-icon-grid rich compact-files"><button class="explorer-file" data-local="clip"><img src="assets/icons/tmp.png" alt=""><span>剪报索引_1996.txt</span></button><button class="explorer-file" data-local="map"><img src="assets/icons/imagefile.png" alt=""><span>南关地图_1994.jpg</span></button></div>`)}
function openLocal(type){minimizedWin=null;winMax=false;win='local:'+type;render()}
function localFileSpec(type){
  const notepad=(title,html)=>({title:title+' - 记事本',type:'notepad',menubar:'<div class="classic-menu">文件(F)　编辑(E)　格式(O)　查看(V)　帮助(H)</div>',body:`<div class="note-paper notepad-paper local-doc">${html}</div>`,status:'Windows (CRLF)　ANSI'});
  const image=(title,src,caption)=>({title:title+' - Windows 图片和传真查看器',type:'photo-viewer',toolbar:'<div class="photo-tools"><button>放大</button><button>缩小</button><button>打印</button></div>',body:`<div class="single-photo-view"><img src="${src}" alt=""><div class="single-photo-caption">${caption}</div></div>`,status:title});
  if(type==='start')return notepad('调查起点.txt',`9/10<br><br>妈那只旧箱子我又翻了一遍。1996年11月那几张剪报先按日期录了，24号写五个孩子，后面几份记录的数字对不上。<br><br>她以前只跟我说过，八岁那年在南关走丢了一次，后来搬了家。转学的事没提过。<br><br>先把报纸、学校和当年的接警记录对一下，别先往传言上靠。`);
  if(type==='clip')return notepad('剪报索引_1996.txt',`1996 / 南关<br><br>11/24　南关五名儿童一度与家长失去联系<br>11/25　关于南关“怪老人”传言的情况说明<br>11/27　南关多名儿童已与家属取得联系<br><br>数字报刊：<button class="file-link" data-web="news">archive.heningdaily.local</button><br><br>另记：11月25日二小有一份三年级考勤汇总，晚报那篇提到了。`);
  if(type==='hehui')return notepad('户籍摘录_何惠.txt',`户籍资料摘录<br><br>姓名：何惠<br>出生日期：1988-03-09<br>1996年登记住址：南关区东河路42号<br>1996年12月迁出。<br><br>抄录日期：2026-09-10。`);
  if(type==='unsorted1')return notepad('待核_0911.txt',`9/11<br><br>2012年10月4日“南关人家”有个旧帖提到早市找孩子，先记在这里。<br><br>旧二路终点这个叫法也出现了。D盘里那份旧备份还没重新看。`);
  if(type==='map')return image('南关地图_1994.jpg','assets/map_1994.jpg','1994年城区图扫描。沈妍在页边写了“旧门牌还是查图书馆地方文献”。');
  if(type==='sicknote'){mark('shenyan_absence');return {title:'请假单_2012.jpg - Windows 图片和传真查看器',type:'photo-viewer',toolbar:'<div class="photo-tools"><button>放大</button><button>缩小</button><button>打印</button></div>',body:`<div class="document-photo"><div class="leave-slip"><div class="slip-school">鹤宁实验小学</div><h2>学生请假单</h2><div class="slip-row"><b>学生姓名</b><span>沈妍</span><b>班级</b><span>一年级二班</span></div><div class="slip-row"><b>请假时间</b><span>2012年10月2日至10月3日</span></div><div class="slip-row"><b>请假事由</b><span>发烧，在家休息</span></div><div class="slip-sign">家长签字：何惠</div></div><div class="single-photo-caption">扫描件。纸张背面没有字。</div></div>`,status:'请假单_2012.jpg'}}
  if(type==='notice'){mark('shenyan_notice');return {title:'寻人启事_排版稿.doc - Microsoft Word',type:'word-viewer',menubar:'<div class="classic-menu">文件(F)　编辑(E)　视图(V)　插入(I)　格式(O)　工具(T)　表格(A)　窗口(W)　帮助(H)</div>',toolbar:'<div class="word-toolbar"><button>打开</button><button>保存</button><button>打印</button><span>宋体　小二　<b>B</b></span></div>',body:`<div class="word-workarea"><article class="word-page missing-notice"><h1>寻 人 启 事</h1><p>沈妍，女，6岁，身高约118厘米。2012年10月2日下午在南关早市附近走失，走失时穿浅灰色外套、红色布鞋。</p><p>如有线索，请联系何女士。</p><p class="word-meta">文件创建：2012-10-02 19:42<br>打印记录：无</p></article></div>`,status:'第1页，共1页'}}
  if(type==='privateMemo'){mark('private_notes');return notepad('调查备忘.txt',`9/11<br><br>请假单写的是发烧。那张寻人启事是2号晚上建的，没有打印记录。<br><br>我小时候问过妈那两天，她一直说我烧得厉害，前面的事记不清。我自己也只记得后来在家里的几天。<br><br>亲戚偶尔叫我“妍妍”，她会马上改口叫沈妍。以前我以为她只是嫌这个小名俗。<br><br>旧日历是她自己的字。4号那张照片还要再核日期。`)}
  if(type==='calendarLocal'){mark('calendar');return {title:'旧日历_2012_10.jpg - Windows 图片和传真查看器',type:'photo-viewer',toolbar:'<div class="photo-tools"><button>放大</button><button>缩小</button><button>打印</button></div>',body:`<div class="diary-photo"><div class="scan diary-scan"><b>何惠旧日历 · 2012年10月</b><p>10月2日　下午没找到。给学校打电话，说发烧。寻人启事排好了，先没印。</p><p>10月3日　15点多，旧二路那边找到。回来不肯进自己房间，晚上在客厅坐到很晚。</p><p>10月4日　早上吃了半碗鸡蛋羹。问她卧室在哪，她先指了厨房那边。后来问我晚上还去不去“原来那个地方”。没再问。</p><p>10月5日　中午叫我妈了。学校说周一能去。</p><p>10月6日　给班主任打电话，这几天先叫沈妍。猫送小妹。南关先不去。</p></div></div>`,status:'旧日历_2012_10.jpg'}}
  return notepad('文件','该文件没有可显示的内容。');
}
function photoHTML(){mark('photo_meta');return `<div class="photo-view-layout"><div class="photo-canvas"><div class="photo-frame"><img src="assets/mother_child_photo.jpg" alt="母女合影"></div></div><aside class="photo-note-panel"><div class="photo-note-title">照片信息</div><dl><dt>文件名</dt><dd>IMG_2002.jpg</dd><dt>拍摄日期</dt><dd>2012-10-04 10:18</dd><dt>相机</dt><dd>Canon DIGITAL IXUS</dd></dl></aside></div>`}
function timelineHTML(){
  const rows=[];
  if(has('news5'))rows.push(['1996.11.24','晚报报道南关五名儿童一度失联','鹤宁晚报']);
  if(has('school6'))rows.push(['1996.11.25','二小三年级异常考勤中有六名学生','校务附件']);
  if(has('teacher'))rows.push(['1996.11.27','何惠返校；住址回答为“槐树巷17号”','班主任工作册']);
  if(has('address_owner'))rows.push(['—','槐树巷17号登记为赵淑琴 / 冯家长期居住','旧门牌表']);
  if(has('neighbor'))rows.push(['2012.10.03','沈妍在旧二路终点附近被找到','南关人家旧帖']);
  if(has('shenyan_notice'))rows.push(['2012.10.02','何惠建立沈妍寻人启事排版稿','本地备份']);
  if(has('calendar'))rows.push(['2012.10.03—10.06','何惠日历记录沈妍回家后的几天','旧日历扫描']);
  const canFinal=state.stage>=7;
  return `<div class="timeline-wrap"><table class="excel-grid"><thead><tr><th class="rowhead"></th><th>A</th><th>B</th><th>C</th></tr><tr><th class="rowhead">1</th><th>时间</th><th>记录</th><th>来源</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><th class="rowhead">${i+2}</th><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}<tr><th class="rowhead">${rows.length+2}</th><td>${has('final_date')?'2012.10.04':canFinal?'<input id="finalDate" inputmode="numeric" placeholder="YYYY-MM-DD">':'（待核）'}</td><td>母女合影</td><td>IMG_2002.jpg</td></tr></tbody></table>
  ${canFinal&&!has('final_date')?'<div class="excel-actionbar"><button id="finalSubmit">写入日期</button><span id="finalMsg">按照片原始信息填写。</span></div>':''}
  ${has('final_date')?`<div class="final-file-row"><span class="final-file-label">附件</span><button id="finalPhoto" class="final-photo-link"><img src="assets/mother_child_photo.jpg" alt="照片缩略图"><span>IMG_2002.jpg</span></button></div>`:''}
  ${has('final_photo')?'<div class="photo-back"><div class="photo-back-label">照片背面</div><div class="photo-back-hand">10.4 早上。回来第二天，肯吃东西了。</div></div><div class="caption">工作簿没有其他附件。</div>':''}</div>`;
}
function privateLoginHTML(){
  if(has('backup_open'))return backupFilesHTML();
  return `<div class="private-screen"><div class="login classic-login"><div class="login-title">BACKUP_OLD</div><p>该目录由旧版本地加密工具保护。备份只读。</p><label>账户名<input id="loginUser" autocomplete="off"></label><label>校验日期 <span>提示：回家那天</span><input id="loginPass" inputmode="numeric" autocomplete="off" placeholder="YYYYMMDD"></label><button id="loginSubmit">确定</button><button class="classic-button" data-open="computer">取消</button><div id="loginMsg" class="login-message"></div></div></div>`;
}
function backupFilesHTML(){return `<div class="backup-open"><div class="backup-banner"><b>BACKUP_OLD</b><span>归档日期：2018-07-04　只读</span></div><div class="explorer-icon-grid rich compact-files backup-files"><button class="explorer-file" data-local="sicknote"><img src="assets/icons/imagefile.png" alt=""><span>请假单_2012.jpg</span></button><button class="explorer-file" data-local="notice"><img src="assets/icons/doc.png" alt=""><span>寻人启事_排版稿.doc</span></button><button class="explorer-file" data-local="privateMemo"><img src="assets/icons/tmp.png" alt=""><span>调查备忘.txt</span></button><button class="explorer-file" data-local="calendarLocal"><img src="assets/icons/imagefile.png" alt=""><span>旧日历_2012_10.jpg</span></button><button class="explorer-file" data-open="photo"><img src="assets/icons/photo.png" alt=""><span>IMG_2002.jpg</span></button></div></div>`}
function searchHTML(){return `<div class="search-dog"><div class="search-pane"><h3>您要查找什么？</h3><label>全部或部分文件名：<input id="localSearchKw" placeholder="例如：何惠 / 1996 / 照片"></label><button id="localSearchBtn" class="classic-button">搜索</button></div><div id="searchResults" class="search-results"><p>在本地磁盘和“我的文档”中搜索。</p></div></div>`}
function bindLocal(){
  document.getElementById('winClose')?.addEventListener('click',closeWin);document.getElementById('winMin')?.addEventListener('click',()=>{minimizedWin=win;win=null;render()});document.getElementById('winMax')?.addEventListener('click',()=>{winMax=!winMax;render()});document.getElementById('resetBtn')?.addEventListener('click',()=>confirm('确定清除当前进度？')&&reset());
  document.querySelectorAll('.window [data-open]').forEach(b=>b.onclick=()=>openWin(b.dataset.open));document.querySelectorAll('[data-local]').forEach(b=>b.onclick=()=>openLocal(b.dataset.local));document.querySelectorAll('[data-web]').forEach(b=>b.onclick=()=>openBrowser(b.dataset.web));
  const st=m=>{const x=document.querySelector('.window-status');if(x)x.textContent=m};document.querySelectorAll('.static-task').forEach(b=>b.onclick=()=>st('项目已重新排列。'));document.querySelectorAll('.xp-tool').forEach(b=>{if(!b.dataset.open)b.onclick=()=>st('当前位置为只读备份。')});
  document.querySelectorAll('.photo-tools button').forEach(b=>b.onclick=()=>{const img=document.querySelector('.photo-viewer .window-body img');if(!img)return;const t=b.textContent.trim();if(t==='打印'){st('未检测到可用打印机。');return}let z=Number(img.dataset.zoom||1);z=t==='放大'?Math.min(2,z+.15):Math.max(.55,z-.15);img.dataset.zoom=z;img.style.transform=`scale(${z})`;st(`缩放 ${Math.round(z*100)}%`)});
  const lsb=document.getElementById('localSearchBtn');if(lsb)lsb.onclick=()=>{const q=(document.getElementById('localSearchKw').value||'').trim();const r=document.getElementById('searchResults');const pool=[{name:'1996资料\\剪报索引_1996.txt',keys:'1996 剪报 南关',open:'local:clip'},{name:'1996资料\\户籍摘录_何惠.txt',keys:'何惠 户籍 1988 东河路',open:'local:hehui'},{name:'沈妍的资料\\调查记录.xls',keys:'调查 记录 时间线',open:'timeline'},...(has('backup_open')?[{name:'D:\\BACKUP_OLD\\IMG_2002.jpg',keys:'照片 IMG_2002 母女',open:'photo'}]:[])];const hit=pool.filter(x=>!q||(x.name+' '+x.keys).includes(q));r.innerHTML=hit.length?hit.map(x=>`<button class="search-hit file-link" style="display:block;width:100%;text-align:left;background:transparent;border:0;border-bottom:1px solid #ddd" data-search-open="${x.open}">${esc(x.name)}</button>`).join(''):'<p>搜索完成。没有找到文件。</p>';r.querySelectorAll('[data-search-open]').forEach(b=>b.onclick=()=>{const v=b.dataset.searchOpen;if(v.startsWith('local:'))openLocal(v.slice(6));else openWin(v)})};
  const fs=document.getElementById('finalSubmit');if(fs)fs.onclick=()=>{const v=document.getElementById('finalDate').value.trim().replace(/[/.]/g,'-');if(v==='2012-10-04'||v==='20121004'){mark('final_date');win='timeline';render()}else document.getElementById('finalMsg').textContent='日期和照片原始信息对不上。'};document.getElementById('finalPhoto')?.addEventListener('click',()=>{mark('final_photo');win='timeline';render()});
  const ls=document.getElementById('loginSubmit');if(ls)ls.onclick=()=>{const u=document.getElementById('loginUser').value.trim().toLowerCase();const p=document.getElementById('loginPass').value.trim().replace(/[-/.]/g,'');if(u==='sy0718'&&p==='20121003'){mark('backup_open');win='private';render()}else document.getElementById('loginMsg').textContent='账户名或校验日期不匹配。'};
}
function siteBase(r){const b=(r||'home').split(':')[0];if(b==='police'||b.startsWith('news'))return'news';if(b==='teacher'||b.startsWith('school'))return'school';if(b==='thread'||b.startsWith('forum'))return'forum';if(b==='libdoc'||b.startsWith('library'))return'library';return b}
function siteLabel(b){return({news:'鹤宁晚报',school:'鹤宁二小',forum:'南关人家',library:'市图书馆'}[b]||b)}
function openBrowser(route,push=true){browserRoute=route||'home';win='browser';minimizedWin=null;const base=siteBase(browserRoute);if(['news','school','forum','library'].includes(base)&&!browserTabs.includes(base))browserTabs.push(base);if(push){historyStack=historyStack.slice(0,historyIndex+1);historyStack.push(browserRoute);historyIndex=historyStack.length-1}render()}
function nav(route){openBrowser(route,true)}
function renderBrowserShell(){
  const bb=browserRoute.split(':')[0],base=siteBase(browserRoute);const title=base==='news'?'鹤宁晚报数字报刊':base==='school'?'鹤宁市第二小学':base==='forum'?'南关人家 - 论坛':base==='library'?'鹤宁市图书馆':'Microsoft Internet Explorer';
  const browser=`<section class="browser-window ${winMax?'maximized':''}"><div class="browser-titlebar"><img src="assets/icons/browser.png" alt=""><strong>${esc(title)} - Microsoft Internet Explorer</strong><div class="browser-window-controls"><button id="browserMin">_</button><button id="browserMax">□</button><button id="browserClose">×</button></div></div><div class="ie-tabs">${browserTabs.map(t=>`<button class="ie-tab ${base===t?'active':''}" data-tab="${t}">${siteLabel(t)}</button>`).join('')}</div><div class="browser-menubar">文件(F)　编辑(E)　查看(V)　收藏(A)　工具(T)　帮助(H)</div><div class="ie-toolbar"><button class="ie-tool" id="backBtn" ${historyIndex<=0?'disabled':''}>◀<small>后退</small></button><button class="ie-tool" id="fwdBtn" ${historyIndex>=historyStack.length-1?'disabled':''}>▶<small>前进</small></button><span class="ie-sep"></span><span class="ie-tool static">■<small>停止</small></span><span class="ie-tool static">↻<small>刷新</small></span><span class="ie-tool static">⌂<small>主页</small></span></div><div class="browser-top"><span class="address-label">地址(D)</span><input id="address" class="address" value="http://${esc(routeUrl(browserRoute))}"><button id="goBtn" class="go">转到</button></div><div class="bookmarkbar"><span class="fav-label">已打开</span>${browserTabs.map(t=>`<button data-nav="${t}">${siteLabel(t)}</button>`).join('')}</div><div id="browserContent" class="browser-content">${renderRoute(browserRoute)}</div><div class="browser-status"><span>完成</span><span>本地缓存：可用　脱机工作</span><span>Internet</span></div></section>`;
  app.innerHTML=desktopHTML()+browser;bindDesktop();bindBrowser();renderAnchor();
}
function routeUrl(r){const [b,a]=r.split(':');if(b==='home')return'about:blank';if(b==='offline')return decodeURIComponent(r.slice(8));if(b==='police')return'archive.heningdaily.local/attachment/ng-police-1996';if(b.startsWith('news'))return'archive.heningdaily.local/'+(b==='news'?'':'view/'+encodeURIComponent(a||''));if(b==='teacher'||b.startsWith('school'))return'old.hn2ps.edu.local/'+(b==='school'?'':'archive/'+b);if(b==='thread'||b.startsWith('forum'))return'bbs.nanguan.local/'+(b==='forum'?'':'thread/'+(a||''));if(b==='libdoc'||b.startsWith('library'))return'lib.hening.local/'+(b==='library'?'':'local/'+(a||''));return'local/'+r}
function fromAddress(v){const raw=v.trim(),x=raw.toLowerCase().replace(/^https?:\/\//,'').replace(/\/$/,'');if(!raw||x==='about:blank')return'home';if(x.startsWith('archive.heningdaily.local'))return'news';if(x.startsWith('old.hn2ps.edu.local'))return'school';if(x.startsWith('bbs.nanguan.local'))return'forum';if(x.startsWith('lib.hening.local'))return'library';return'offline:'+encodeURIComponent(raw)}
function bindBrowser(){
  document.getElementById('browserClose').onclick=()=>{win=null;winMax=false;render()};document.getElementById('browserMin').onclick=()=>{minimizedWin='browser';win=null;render()};document.getElementById('browserMax').onclick=()=>{winMax=!winMax;renderBrowserShell()};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>nav(b.dataset.tab));document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));document.getElementById('goBtn').onclick=()=>nav(fromAddress(document.getElementById('address').value));document.getElementById('address').onkeydown=e=>{if(e.key==='Enter')nav(fromAddress(e.currentTarget.value))};document.getElementById('backBtn').onclick=()=>{if(historyIndex>0){historyIndex--;browserRoute=historyStack[historyIndex];renderBrowserShell()}};document.getElementById('fwdBtn').onclick=()=>{if(historyIndex<historyStack.length-1){historyIndex++;browserRoute=historyStack[historyIndex];renderBrowserShell()}};bindRoute(browserRoute)
}
function renderRoute(r){const [b,a]=r.split(':');if(b==='home')return browserHome();if(b==='offline')return browserOffline(decodeURIComponent(r.slice(8)));if(b==='news')return newsHome();if(b==='newsarticle')return newsArticle(a);if(b==='newssearch')return newsSearch(a);if(b==='police')return policeDoc();if(b==='school')return schoolHome();if(b==='schoolarchive')return schoolArchive();if(b==='schoolstudent')return schoolStudent();if(b==='teacher')return teacherRecord();if(b==='schoolnotice')return schoolNotice(a);if(b==='forum')return forumHome();if(b==='forumsearch')return forumSearch(a);if(b==='thread')return forumThread(a);if(b==='library')return libraryHome();if(b==='librarysearch')return librarySearch(a);if(b==='libdoc')return libraryDoc(a);return browserHome()}
function browserHome(){return `<div class="ie-home"><div class="ie-home-logo">Microsoft Internet Explorer</div><h2>脱机工作</h2><p>这台电脑没有连接互联网。已经保存过的网页仍可打开。</p></div>`}
function browserOffline(v){return `<div class="ie-error"><h2>无法显示网页</h2><p>Internet Explorer 无法打开 <b>${esc(v)}</b>。</p><hr><p>该地址没有保存在本机缓存中。</p></div>`}
const normalNews=[['1996-11-29','市公交公司增开冬季早班车','民生'],['1996-11-28','鹤宁纺织厂完成锅炉改造','经济'],['1996-11-27','南关多名儿童已与家属取得联系','社会'],['1996-11-26','校方提醒家长接送低年级学生','教育'],['1996-11-25','关于南关“怪老人”传言的情况说明','社会'],['1996-11-24','南关五名儿童一度与家长失去联系','社会'],['1996-11-23','冬储白菜进入集中上市期','民生'],['1996-11-22','青年宫周末开放乒乓球馆','文体'],['1996-11-21','鹤宁今冬首场降雪预计周末到来','天气'],['1996-11-20','市环卫处调整冬季清扫时间','民生']];
function newsHome(){return `<div class="site news"><div class="mast"><div class="brand">鹤宁晚报</div><div class="mast-meta">HENING EVENING NEWS</div><div class="issue-date">历史数字报刊</div><div class="news-quick-search"><input id="newsKw" placeholder="站内搜索"><button id="newsSearch" class="action">搜索</button></div></div><div class="subnav"><span>首页</span><span>本地新闻</span><span>社会</span><span>民生</span><span>文体</span><span>旧版检索</span></div><div class="wrap"><h2>1996年11月</h2><div class="news-list">${normalNews.map(n=>`<div class="news-row"><div class="date">${n[0]}</div><div><button class="linklike" data-news="${n[0]}">${n[1]}</button><div class="muted">${n[2]} · 历史版面</div></div></div>`).join('')}</div></div></div>`}
function newsSearch(q=''){const kw=decodeURIComponent(q||'').trim();const rows=normalNews.filter(n=>!kw||n.join(' ').includes(kw)||(/南关|儿童|老人|猫脸/.test(kw)&&/南关|儿童|怪老人/.test(n[1])));return `<div class="site news"><div class="mast"><div class="brand">鹤宁晚报</div><div>数字报刊资料库</div></div><div class="wrap"><p><button class="linklike" data-nav="news">← 返回</button></p><h2>检索结果：${esc(kw)}</h2>${rows.map(n=>`<div class="news-row"><div class="date">${n[0]}</div><div><button class="linklike" data-news="${n[0]}">${n[1]}</button></div></div>`).join('')||'<p>没有匹配结果。</p>'}</div></div>`}
function newsArticle(date){
  const common=`<div class="site news"><div class="mast"><div class="brand">鹤宁晚报</div><div class="mast-meta">HENING EVENING NEWS</div><div class="issue-date">历史数字报刊</div></div><div class="subnav"><span>本地新闻</span><span>社会</span><span>民生</span><span>文体</span><span>旧版检索</span></div><div class="wrap article"><button class="linklike" data-nav="news">← 返回数字报刊</button>`;
  if(date==='1996-11-24'){mark('news5');return common+`<h1 class="headline">南关五名儿童一度与家长失去联系</h1><div class="muted">1996-11-24 · 社会版</div><p>本报讯　昨日傍晚，南关一带有五名低龄儿童在放学、买菜及外出途中一度与家长失去联系。家属、学校和辖区民警连夜寻找，截至今晨已有两名儿童由家属自行接回，其余情况仍在核实。</p><p>鹤宁第二小学称，23日至24日低年级有数名学生未到校，原因包括病假、家长寻找和去向未明。学校已要求低年级学生放学后由家长接送。</p><p>警方提醒居民不要把近期流传的“怪老人抓孩子”等说法与正在核实的走失情况混在一起。</p><div class="archive-source-box"><b>相关资料</b><span>鹤宁二小旧站保存有当周校务附件。</span><button class="linklike" data-nav="school">鹤宁第二小学旧官网镜像</button></div></div></div>`}
  if(date==='1996-11-25')return common+`<h1 class="headline">关于南关“怪老人”传言的情况说明</h1><div class="muted">1996-11-25 · 社会版</div><p>南关街道办昨日对近期传言作出说明。居民反映的一名老妇人为赵淑琴，近期确曾在南关多处询问儿童下落。</p><p>经核实，赵淑琴的外孙女冯小兰于11月23日傍晚未归。赵本人于24日清晨突发疾病，经抢救无效死亡。街道工作人员表示，赵淑琴面部旧疾与儿童失联没有证据上的联系。</p><p>有关“猫脸老人”“夜间追孩子”等说法目前均无事实依据。</p><div style="display:flex;gap:16px;align-items:flex-start;flex-wrap:wrap"><img src="assets/zhao_newsprint_photo.jpg" alt="报纸中的赵淑琴旧照" style="width:145px;border:1px solid #777;background:#ddd;padding:3px"><div class="muted" style="max-width:420px">报刊资料图。原扫描有折痕和网点重影。</div></div></div></div>`;
  if(date==='1996-11-27')return common+`<h1 class="headline">南关多名儿童已与家属取得联系</h1><div class="muted">1996-11-27 · 社会版</div><p>截至昨晚，此前一度与家长失去联系的儿童已有四人与家属团聚，另有一名仍在寻找。</p><p>辖区民警表示，媒体早期统计、学校缺勤登记和正式接警数量并不一致。部分家属先自行寻找，找到后才电话告知值班人员，因此没有生成正式案号。</p><p>公开摘录：<button class="linklike" data-nav="police">南关辖区1996年11月接处警摘要</button></p></div></div>`;
  const n=normalNews.find(n=>n[0]===date);return common+`<h1 class="headline">${esc(n?.[1]||'历史报道')}</h1><div class="muted">${esc(date)} · ${esc(n?.[2]||'本地')}</div><p>本报讯　该版面为地方新闻存档。原件由市图书馆报刊库保存。</p></div></div>`;
}
function policeDoc(){mark('police4');return `<div class="site library"><div class="head"><div class="libname">鹤宁市公开资料镜像</div></div><div class="wrap"><div class="doc-view"><div style="text-align:center"><h2>南关辖区 1996 年 11 月接处警摘要</h2><div class="muted">公开摘录 / 后期数字化</div></div><table class="school-table" style="margin-top:24px"><tr><th>日期</th><th>编号</th><th>事项</th><th>结果</th></tr><tr><td>11/23</td><td>NG961123-07</td><td>儿童走失</td><td>转失踪登记</td></tr><tr><td>11/23</td><td>NG961123-11</td><td>儿童走失</td><td>次日家属带回</td></tr><tr><td>11/24</td><td>NG961124-02</td><td>儿童走失</td><td>转失踪登记</td></tr><tr><td>11/24</td><td>NG961124-04</td><td>儿童走失</td><td>继续查找</td></tr><tr><td>11/24</td><td>口头求助</td><td>何姓家属称女童未归</td><td>后电话称已找到，未生成案号</td></tr></table></div></div></div>`}
const schoolNotices=[['2012-06-28','关于暑期校舍安全检查的通知'],['2011-09-01','新学期开学工作安排'],['2010-12-03','冬季传染病防控告家长书'],['2009-05-12','校园消防疏散演练情况'],['1999-12-20','校史资料整理征集启事'],['1996-12-02','关于加强低年级放学管理的通知']];
function schoolHome(){return `<div class="site school"><div class="header"><div class="head-inner"><div class="school-seal">鹤<br>二</div><div class="school-name-wrap"><div class="school-name">鹤宁市第二小学</div><div class="school-en">HENING NO.2 PRIMARY SCHOOL</div></div><div class="school-slogan"><b>团结　勤学　健康　快乐</b></div></div></div><div class="school-topnav"><span>学校首页</span><span>学校概况</span><span>通知公告</span><span>教学教研</span><span>教师园地</span><span>旧版资料</span></div><div class="wrap"><div class="school-grid"><aside class="leftmenu"><div>学校首页</div><div>学校概况</div><div>通知公告</div><div><button class="linklike" data-nav="schoolarchive">旧版资料</button></div><div>联系我们</div></aside><section class="school-content"><h2>通知公告</h2><div class="ordinary-list">${schoolNotices.map((x,i)=>`<div><span class="date">${x[0]}</span><button class="linklike" data-schoolnotice="${i}">· ${x[1]}</button></div>`).join('')}</div><div class="school-bottom-strip"><span>校务公开</span><span>家校交流</span><span>卫生保健</span><span>少先队</span></div></section></div><div class="old-counter">建议使用 IE6 / 1024×768 浏览</div></div></div>`}
function schoolNotice(i){const x=schoolNotices[Number(i)]||schoolNotices[0];return `<div class="site school"><div class="header"><div class="head-inner"><div class="school-name">鹤宁市第二小学</div></div></div><div class="wrap"><p><button class="linklike" data-nav="school">← 返回首页</button></p><div class="old-article"><h1>${esc(x[1])}</h1><div class="school-meta">发布时间：${esc(x[0])}　来源：校办公室</div><p>本通知由校办公室发布，请各班按要求执行。具体名单和附件以校内纸质通知为准。</p></div></div></div>`}
function schoolArchive(){return `<div class="site school"><div class="header"><div class="head-inner"><div class="school-name">鹤宁市第二小学</div></div></div><div class="nav"><div class="wrap"><span>学校首页</span><span>校史资料</span><span>旧附件镜像</span></div></div><div class="wrap"><div class="crumb">首页 &gt; 校史资料 &gt; 旧附件镜像</div><h2 style="font-size:18px;color:#174d75">1996年校务附件</h2><p>2009年整理校史资料时建立的扫描索引。纸卡缺项按原样保留。</p><div class="main-grid"><div><div class="table-scroll"><table class="school-table"><tr><th>文件</th><th>日期</th><th>类型</th></tr><tr><td><button class="linklike attach" id="absenceOpen">1996-11-25_三年级考勤汇总.xls</button></td><td>1996-11-25</td><td>XLS</td></tr><tr><td>1996-11_低年级放学管理通知.doc</td><td>1996-11-26</td><td>DOC</td></tr><tr><td>1996-12_转学办理汇总.xls</td><td>1996-12-06</td><td>XLS</td></tr></table></div><h3 style="margin-top:24px;font-size:15px">旧学籍查询</h3><div class="search-row"><label>学生姓名<input id="studentName" placeholder="学生姓名"></label><label>出生日期<input id="studentDob" inputmode="numeric" placeholder="YYYYMMDD"></label><button class="action" id="studentSearch">查询</button></div><div id="studentMsg" class="caption"></div></div><aside class="side"><b>资料说明</b><p>旧系统只支持姓名与出生日期联合校验。</p></aside></div><div id="absenceArea" style="margin-top:22px"></div></div></div>`}
function absenceTable(){mark('school6');return `<div class="scan registry-scan"><b>三年级11月25日考勤异常汇总</b><table class="school-table" style="margin-top:14px"><tr><th>姓名</th><th>班级</th><th>连续缺勤</th><th>备注</th></tr><tr><td>何惠</td><td>三(2)</td><td>2天</td><td>家属寻找</td></tr><tr><td>冯小兰</td><td>三(1)</td><td>3天+</td><td>未归</td></tr><tr><td>周斌</td><td>三(4)</td><td>1天</td><td>家属已接回</td></tr><tr><td>陈晓梅</td><td>三(3)</td><td>1天</td><td>家属已接回</td></tr><tr><td>王涛</td><td>三(1)</td><td>2天</td><td>家属寻找</td></tr><tr><td>李文杰</td><td>三(2)</td><td>3天</td><td>市二院肺炎住院</td></tr></table><p class="muted">病假、家属寻找和未归都记在同一张异常考勤表里。</p></div>`}
function schoolStudent(){mark('hehui');return `<div class="site school"><div class="header"><div class="head-inner"><div class="school-name">鹤宁市第二小学</div><div class="school-slogan"><b>旧版校史资料</b></div></div></div><div class="wrap"><p><button class="linklike" data-nav="schoolarchive">← 返回旧版资料</button></p><h2>学生历史记录：何惠</h2><table class="school-table"><tr><th>姓名</th><td>何惠</td><th>出生</th><td>1988-03-09</td></tr><tr><th>原班级</th><td>三年级二班</td><th>状态</th><td>1996-11-29 转出</td></tr><tr><th>异常缺勤</th><td>11/23傍晚起，约41小时</td><th>家属备注</th><td>11/25上午已找到</td></tr></table><div class="school-download-box"><b>关联附件</b><button class="linklike" data-nav="teacher">班主任工作记录_1996-11-27.pdf</button><span>转学申请备注：近期不再向学生本人询问走失经过。</span></div></div></div>`}
function teacherRecord(){mark('teacher');return `<div class="site school"><div class="header"><div class="head-inner"><div class="school-name">鹤宁市第二小学</div><div class="school-slogan"><b>校史资料扫描件</b></div></div></div><div class="wrap"><p><button class="linklike" data-nav="schoolarchive">← 返回目录</button></p><div class="scan-reader"><div class="scan-toolbar">第18 / 64页　100%</div><div class="scan stamp"><p>11月27日　何惠今天返校，精神一般。早读点名时按平时叫“惠惠”，没有答，改叫何惠后才答到。</p><p>第一节前坐到第三排靠窗的位置，孙雪提醒后回到原座。</p><p>午饭后问家庭住址，回答“槐树巷17号”。学籍卡登记的是东河路42号，再问一次，仍答槐树巷17号。</p><p>下午家长来校。我把地址的事说了。家长让老师这几天不要再问走失经过，在校先叫全名。29日转学手续已联系教务处。</p></div><p class="muted">记录人：三年级二班班主任。2009年校史资料整理时扫描。</p><div class="school-download-box"><b>整理备注</b><span>旧街门牌核对来源：鹤宁市图书馆地方文献中心。</span><button class="linklike" data-nav="library">地方文献中心</button></div></div></div></div>`}
const forumThreads=[['2012-10-04','南关早市附近昨天是不是在找孩子？','槐树下喝茶',18],['2012-09-28','二路车终点到底搬哪儿了','老何修车',9],['2005-11-21','九几年那个猫脸老太太到底怎么传起来的','锅炉房老李',47],['2003-06-07','鹤宁二小以前是不是有个后门？','南关照相馆',21],['2001-02-03','槐树巷拆迁前老门牌谁还记得','旧邮局',33],['2009-12-02','南关哪家修收音机还行','东河口',7],['2007-06-18','早市搬了以后买菜真麻烦','小叶子',22],['2004-09-19','求推荐给孩子补习作文的老师','秋雨',16]];
function forumHome(){return `<div class="site forum"><div class="topline">南关人家　&gt;　论坛首页　　欢迎，游客　 <span>注册 | 登录 | 社区服务 | 帮助</span></div><div class="wrap"><div class="logo"><b>南关人家</b><span>一起说说我们身边的事</span></div><div class="forum-nav"><span>论坛首页</span><span>生活休闲</span><span>本地新闻</span><span>房屋租售</span><span>亲子教育</span></div><div class="bbs-tools"><input id="forumKw" placeholder="帖子 / 用户 / 街道"><button id="forumSearch" class="action">搜索老帖</button>　主题 18,642</div><div class="thread-list">${forumThreads.slice(1).map((t,j)=>{const i=j+1;return `<div class="thread-row"><div><button class="linklike" data-thread="${i}">${t[1]}</button><div class="muted">${t[0]}</div></div><div>${t[2]}</div><div>${t[3]} 回复</div></div>`}).join('')}</div></div></div>`}
function forumSearch(q=''){const kw=decodeURIComponent(q||'').trim();const inds=forumThreads.map((t,i)=>[t,i]).filter(([t])=>!kw||t.slice(0,3).join(' ').includes(kw)||(/兰兰|猫脸|老太太/.test(kw)&&/猫脸/.test(t[1]))||(/2012|早市|孩子|走失/.test(kw)&&/找孩子/.test(t[1]))||(/槐树巷|门牌/.test(kw)&&/槐树巷/.test(t[1]))).map(x=>x[1]);return `<div class="site forum"><div class="topline">南关人家 BBS · 搜索</div><div class="wrap"><p><button class="linklike" data-nav="forum">← 返回论坛</button></p><h3>搜索：${esc(kw)}</h3><div class="thread-list">${inds.length?inds.map(i=>{const t=forumThreads[i];return `<div class="thread-row"><div><button class="linklike" data-thread="${i}">${t[1]}</button><div class="muted">${t[0]}</div></div><div>${t[2]}</div><div>${t[3]} 回复</div></div>`}).join(''):'<div class="bbs-empty">没有找到符合条件的帖子。</div>'}</div></div></div>`}
function post(user,time,body){return `<div class="post"><div class="post-user"><b>${esc(user)}</b><br><span class="muted">注册居民</span></div><div class="post-body"><span class="floor">${esc(time)}</span>${body}<div class="sig">来自：鹤宁 · 南关</div></div></div>`}
function forumThread(i){i=Number(i);const t=forumThreads[i]||forumThreads[1];let posts='';if(i===2){mark('zhao');posts=`${post('锅炉房老李','2005-11-21 21:08','我那年在锅炉房上夜班，见过赵淑琴两回。她逢人就问兰兰回去了没有，我还回她说没见着。后来才知道兰兰是她外孙女。')}${post('旧邮局','2005-11-21 21:44','她问的确实是“回去了没有”。我家那口子当时还说她是不是急糊涂了。')}${post('槐树下喝茶','2005-11-22 08:16','冯小兰，二小三年级一班的。赵家以前住槐树巷，具体门牌我记不住。老太太第二天清早就没了。')}${post('南关照相馆','2005-11-22 10:26','猫脸那个版本是后来越传越多。守灵院里跑进去一只猫这事有人见过，和孩子走失是不是一回事就不知道了。图书馆地方文献中心后来收过一批南关老人访谈。')}`}
  else if(i===0){mark('neighbor');posts=`${post('槐树下喝茶','2012-10-04 07:21','昨天下午去西郊旧二路终点买零件，看见那边围了几个人。一个女的抱着小姑娘哭，听说是前天下午在南关早市走散的。')}${post('南关照相馆','2012-10-04 09:18','是不是东河路何家的？2号晚上确实有人在早市附近问孩子，我没见他们贴纸。')}${post('槐树下喝茶','2012-10-04 10:40','应该是。小姑娘没看出受伤，就是不肯上她妈的车。她妈说“回家了”，小姑娘问了一句“还是回你家吗”。后来怎么走的我没注意。')}`}
  else{const ordinary={1:['现在改到东河桥那边折返了，旧牌子还在。','老何修车','司机一般不叫“旧二路终点”了。'],3:['后门在操场北边，九十年代末砌墙封了。','南关照相馆','以前放学有人从那边抄近路。'],4:['拆之前门牌是有点乱。17号靠里，送信得从井台旁边拐。','旧邮局','我只记得赵家在那一片，具体哪年搬的不清楚。'],5:['东河口老周还修。','东河口','先把收音机型号说一下。'],6:['桥底那个早市周六人还是多。','小叶子','早点去，不然不好停车。'],7:['实验小学门口有个退休语文老师。','秋雨','三年级以上可以问问。']}[i]||['没人回复。',t[2],''];posts=`${post(t[2],t[0]+' 18:20',ordinary[0])}${post(ordinary[1],t[0]+' 19:03',ordinary[2])}`}
  return `<div class="site forum"><div class="topline">南关人家　&gt;　本地话题　　欢迎，游客</div><div class="wrap"><div class="logo compact-logo"><b>南关人家</b><span>一起说说我们身边的事</span></div><div class="bbs-breadcrumb"><button class="linklike" data-nav="forum">南关人家</button> &gt; 本地话题</div><div class="thread-title-old"><h2>${esc(t[1])}</h2><span>查看：${t[3]*37}　回复：${t[3]}</span></div>${posts}</div></div>`}
const libEntries=[['HN-NG-2001-017','《南关街道旧门牌对照表（1987—2000）》','地方文献'],['HN-ALM-2008-01','《鹤宁地方习俗资料汇编》','地方志'],['HN-MEM-2010-09','南关居民口述资料第九辑','口述史'],['HN-LD-1996-112','《鹤宁晚报》1996年11月合订本','报刊缩微'],['HN-EDU-1996-04','鹤宁第二小学1996年校务附件镜像','教育档案'],['HN-MAP-1994-02','鹤宁市区街巷图1994修订版','地图']];
function libraryHome(){return `<div class="site library"><div class="head"><div class="libname">鹤宁市图书馆 · 地方文献中心</div></div><div class="nav">馆藏目录　数字报刊　地方志　旧地图　社区资料　读者服务</div><div class="wrap"><h2>地方文献联合检索</h2><div class="search-row"><label>题名 / 关键词<input id="libKw" placeholder="题名 / 关键词"></label><button class="action" id="libSearch">检索</button></div><div style="margin-top:24px">${libEntries.map((x,i)=>`<div class="lib-result"><div class="lib-code">${x[0]}</div><button class="linklike" data-lib="${i}">${x[1]}</button><div class="muted">${x[2]} · 馆内阅览 / 数字镜像</div></div>`).join('')}</div></div></div>`}
function librarySearch(q=''){const kw=decodeURIComponent(q||'').trim();const inds=libEntries.map((x,i)=>[x,i]).filter(([x,i])=>!kw||x.join(' ').includes(kw)||(/槐树巷|门牌|17号/.test(kw)&&i===0)||(/乳名|小名|称呼|走失/.test(kw)&&i===1)).map(x=>x[1]);return `<div class="site library"><div class="head"><div class="libname">鹤宁市图书馆 · 检索结果</div></div><div class="wrap"><p><button class="linklike" data-nav="library">← 返回</button></p><h2>关键词：${esc(kw)}</h2>${inds.length?inds.map(i=>{const x=libEntries[i];return `<div class="lib-result"><div class="lib-code">${x[0]}</div><button class="linklike" data-lib="${i}">${x[1]}</button><div class="muted">${x[2]}</div></div>`}).join(''):'<p>未找到匹配书目。</p>'}</div></div>`}
function libraryDoc(i){i=Number(i);let body='';if(i===0){mark('address_owner');body=`<h2>南关街道旧门牌对照表（1987—2000）</h2><table class="school-table"><tr><th>旧址</th><th>登记户主 / 使用人</th><th>备注</th></tr><tr><td>槐树巷15号</td><td>钱守义</td><td>1999年改南关路88号</td></tr><tr><td><b>槐树巷17号</b></td><td><b>赵淑琴 / 冯家</b></td><td>长期居住，后拆除</td></tr><tr><td>槐树巷19号</td><td>街道仓房</td><td>拆除</td></tr><tr><td>东河路42号</td><td>何家</td><td>1996年底迁出</td></tr></table><p class="muted">2001年补录时曾参考南关社区旧帖的门牌讨论。</p><p><button class="linklike" data-nav="forum">南关人家旧论坛镜像</button></p>`}
  else if(i===1){mark('folkname');body=`<h2>《鹤宁地方习俗资料汇编》· 儿童称呼</h2><p class="muted">馆藏号 HN-ALM-2008-01　纸本第84—87页</p><div class="scan"><p><b>采访对象：</b>周桂香，女，1934年生，南关居民。</p><p><b>问：</b>孩子走丢找回来以后，有没有先不叫小名的说法？</p><p><b>答：</b>有些老人讲过。我们家以前碰上孩子受惊，就先叫学名，过几天吃饭睡觉都正常了，再照旧叫。别家怎么做我说不准。</p><p><b>问：</b>为什么？</p><p><b>答：</b>老人说刚受过惊，别老拿小名喊。那时候家里老人怎么交代，大人就怎么做，也不是家家都这样。</p><p><b>整理说明：</b>同批访谈中说法并不一致，部分家庭只在孩子受惊、走失后短期改称大名。</p></div>`}
  else if(i===2)body=`<h2>南关居民口述资料第九辑</h2><p>收录2008—2010年社区交通、早市、拆迁和学校旧址访谈。部分附件为居民保存的论坛打印页。</p><p class="muted">索引词：南关早市；旧二路终点；二小后门；槐树巷。</p>`;
  else{const d=libEntries[i];body=`<h2>${esc(d?.[1]||'地方文献')}</h2><p>馆藏号：${esc(d?.[0]||'—')}　资料类型：${esc(d?.[2]||'地方资料')}</p><p>数字镜像仅供阅览。纸本原件保存于地方文献库。</p>`}
  return `<div class="site library"><div class="head"><div class="libname">鹤宁市图书馆 · 地方文献中心</div></div><div class="nav">馆藏目录　数字报刊　地方志　旧地图　社区资料　读者服务</div><div class="wrap"><div class="lib-breadcrumb"><button class="linklike" data-nav="library">地方文献首页</button> &gt; 馆藏阅览</div><div class="library-reader"><aside><b>文献工具</b><p>馆藏信息</p><p>引用格式</p><p>打印本页</p></aside><div class="doc-view">${body}</div></div></div></div>`}
function bindRoute(){
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));document.querySelectorAll('[data-news]').forEach(b=>b.onclick=()=>nav('newsarticle:'+b.dataset.news));document.querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>nav('thread:'+b.dataset.thread));document.querySelectorAll('[data-lib]').forEach(b=>b.onclick=()=>nav('libdoc:'+b.dataset.lib));document.querySelectorAll('[data-schoolnotice]').forEach(b=>b.onclick=()=>nav('schoolnotice:'+b.dataset.schoolnotice));
  const doNews=()=>nav('newssearch:'+encodeURIComponent(document.getElementById('newsKw').value.trim()));document.getElementById('newsSearch')?.addEventListener('click',doNews);document.getElementById('newsKw')?.addEventListener('keydown',e=>{if(e.key==='Enter')doNews()});
  const doForum=()=>nav('forumsearch:'+encodeURIComponent(document.getElementById('forumKw').value.trim()));document.getElementById('forumSearch')?.addEventListener('click',doForum);document.getElementById('forumKw')?.addEventListener('keydown',e=>{if(e.key==='Enter')doForum()});
  const doLib=()=>nav('librarysearch:'+encodeURIComponent(document.getElementById('libKw').value.trim()));document.getElementById('libSearch')?.addEventListener('click',doLib);document.getElementById('libKw')?.addEventListener('keydown',e=>{if(e.key==='Enter')doLib()});
  document.getElementById('absenceOpen')?.addEventListener('click',()=>{document.getElementById('absenceArea').innerHTML=absenceTable();renderAnchor()});
  const doStudent=()=>{const n=document.getElementById('studentName').value.trim(),d=document.getElementById('studentDob').value.trim().replace(/[-/.]/g,'');if(n==='何惠'&&d==='19880309')nav('schoolstudent');else document.getElementById('studentMsg').textContent='未找到匹配记录。请核对姓名与出生日期。'};document.getElementById('studentSearch')?.addEventListener('click',doStudent);['studentName','studentDob'].forEach(id=>document.getElementById(id)?.addEventListener('keydown',e=>{if(e.key==='Enter')doStudent()}));
}
function renderEnd(){app.innerHTML=`<div class="end-screen" style="background:#0d2231 url('assets/wallpaper.jpg') center/cover no-repeat"><div class="end-inner"><div style="font-size:12px;color:#9aa8b0;margin-bottom:22px">Windows 已锁定</div><div class="photo-frame" style="padding:5px;border-color:#8aa0ad;background:#dfe7ea"><img src="assets/mother_child_photo.jpg" alt="母女合影" style="width:152px;max-width:42vw"></div><div style="font-size:21px;margin-top:12px;text-shadow:0 1px 2px #000">沈妍</div><div class="end-note">照片拍摄于2012年10月4日。</div><div class="end-small">沈妍目前没有新的消息。旧电脑已交还家属。</div><div style="margin-top:54px;color:#a9b2b7;font-size:11px">结束</div><button id="restartEnd" style="margin-top:17px;background:rgba(20,30,36,.56);border:1px solid #6d7d85;color:#c4cbd0;padding:6px 11px">重新开始</button></div></div>`;document.getElementById('restartEnd').onclick=()=>confirm('确定重新开始？')&&reset()}
['pointerdown','keydown','wheel','touchstart'].forEach(ev=>document.addEventListener(ev,noteActivity,{passive:true}));armIdleHint();render();
})();
